// Vulkan Extension Loader (Vexel)

// Copyright © 2024 Rene Lindsay (rjklindsay@hotmail.com)
// Report bugs and download new versions at https://github.com/renelindsay/Vexel
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This file was generated by vexel_gen.py
// For Vulkan header version: 307

#ifdef __cplusplus
extern "C" {
#endif

#ifdef _WIN32
    #define WIN32_LEAN_AND_MEAN
    #include <windows.h>
    FARPROC __stdcall dlsym(HMODULE lib, LPCSTR fn) { return GetProcAddress(lib, fn); }
    HMODULE LoadVulkan(){return LoadLibrary("vulkan-1.dll");}
#else
    #include <dlfcn.h>
    void* LoadVulkan(){
        void*    lib = dlopen("libvulkan.so", RTLD_NOW | RTLD_LOCAL);
        if(!lib) lib = dlopen("libvulkan.so.1", RTLD_NOW | RTLD_LOCAL);
        return lib;
    }
#endif

#include "vexel.h"

struct AutoRun{AutoRun(){ vexInitialize(); }}AutoRun;  // Run vexInitialize() at startup.

bool vexInitialize(void) {
    auto libvulkan = LoadVulkan();
    if (!libvulkan) return false;

    // Set Vulkan function pointers to use loader for dispatch
    #define LOAD(PROC) PROC = (PFN_##PROC) dlsym(libvulkan, #PROC);
    LOAD(vkCreateInstance)
    LOAD(vkDestroyInstance)
    LOAD(vkEnumeratePhysicalDevices)
    LOAD(vkGetPhysicalDeviceFeatures)
    LOAD(vkGetPhysicalDeviceFormatProperties)
    LOAD(vkGetPhysicalDeviceImageFormatProperties)
    LOAD(vkGetPhysicalDeviceProperties)
    LOAD(vkGetPhysicalDeviceQueueFamilyProperties)
    LOAD(vkGetPhysicalDeviceMemoryProperties)
    LOAD(vkGetInstanceProcAddr)
    LOAD(vkGetDeviceProcAddr)
    LOAD(vkCreateDevice)
    LOAD(vkDestroyDevice)
    LOAD(vkEnumerateInstanceExtensionProperties)
    LOAD(vkEnumerateDeviceExtensionProperties)
    LOAD(vkEnumerateInstanceLayerProperties)
    LOAD(vkEnumerateDeviceLayerProperties)
    LOAD(vkGetDeviceQueue)
    LOAD(vkQueueSubmit)
    LOAD(vkQueueWaitIdle)
    LOAD(vkDeviceWaitIdle)
    LOAD(vkAllocateMemory)
    LOAD(vkFreeMemory)
    LOAD(vkMapMemory)
    LOAD(vkUnmapMemory)
    LOAD(vkFlushMappedMemoryRanges)
    LOAD(vkInvalidateMappedMemoryRanges)
    LOAD(vkGetDeviceMemoryCommitment)
    LOAD(vkBindBufferMemory)
    LOAD(vkBindImageMemory)
    LOAD(vkGetBufferMemoryRequirements)
    LOAD(vkGetImageMemoryRequirements)
    LOAD(vkGetImageSparseMemoryRequirements)
    LOAD(vkGetPhysicalDeviceSparseImageFormatProperties)
    LOAD(vkQueueBindSparse)
    LOAD(vkCreateFence)
    LOAD(vkDestroyFence)
    LOAD(vkResetFences)
    LOAD(vkGetFenceStatus)
    LOAD(vkWaitForFences)
    LOAD(vkCreateSemaphore)
    LOAD(vkDestroySemaphore)
    LOAD(vkCreateEvent)
    LOAD(vkDestroyEvent)
    LOAD(vkGetEventStatus)
    LOAD(vkSetEvent)
    LOAD(vkResetEvent)
    LOAD(vkCreateQueryPool)
    LOAD(vkDestroyQueryPool)
    LOAD(vkGetQueryPoolResults)
    LOAD(vkCreateBuffer)
    LOAD(vkDestroyBuffer)
    LOAD(vkCreateBufferView)
    LOAD(vkDestroyBufferView)
    LOAD(vkCreateImage)
    LOAD(vkDestroyImage)
    LOAD(vkGetImageSubresourceLayout)
    LOAD(vkCreateImageView)
    LOAD(vkDestroyImageView)
    LOAD(vkCreateShaderModule)
    LOAD(vkDestroyShaderModule)
    LOAD(vkCreatePipelineCache)
    LOAD(vkDestroyPipelineCache)
    LOAD(vkGetPipelineCacheData)
    LOAD(vkMergePipelineCaches)
    LOAD(vkCreateGraphicsPipelines)
    LOAD(vkCreateComputePipelines)
    LOAD(vkDestroyPipeline)
    LOAD(vkCreatePipelineLayout)
    LOAD(vkDestroyPipelineLayout)
    LOAD(vkCreateSampler)
    LOAD(vkDestroySampler)
    LOAD(vkCreateDescriptorSetLayout)
    LOAD(vkDestroyDescriptorSetLayout)
    LOAD(vkCreateDescriptorPool)
    LOAD(vkDestroyDescriptorPool)
    LOAD(vkResetDescriptorPool)
    LOAD(vkAllocateDescriptorSets)
    LOAD(vkFreeDescriptorSets)
    LOAD(vkUpdateDescriptorSets)
    LOAD(vkCreateFramebuffer)
    LOAD(vkDestroyFramebuffer)
    LOAD(vkCreateRenderPass)
    LOAD(vkDestroyRenderPass)
    LOAD(vkGetRenderAreaGranularity)
    LOAD(vkCreateCommandPool)
    LOAD(vkDestroyCommandPool)
    LOAD(vkResetCommandPool)
    LOAD(vkAllocateCommandBuffers)
    LOAD(vkFreeCommandBuffers)
    LOAD(vkBeginCommandBuffer)
    LOAD(vkEndCommandBuffer)
    LOAD(vkResetCommandBuffer)
    LOAD(vkCmdBindPipeline)
    LOAD(vkCmdSetViewport)
    LOAD(vkCmdSetScissor)
    LOAD(vkCmdSetLineWidth)
    LOAD(vkCmdSetDepthBias)
    LOAD(vkCmdSetBlendConstants)
    LOAD(vkCmdSetDepthBounds)
    LOAD(vkCmdSetStencilCompareMask)
    LOAD(vkCmdSetStencilWriteMask)
    LOAD(vkCmdSetStencilReference)
    LOAD(vkCmdBindDescriptorSets)
    LOAD(vkCmdBindIndexBuffer)
    LOAD(vkCmdBindVertexBuffers)
    LOAD(vkCmdDraw)
    LOAD(vkCmdDrawIndexed)
    LOAD(vkCmdDrawIndirect)
    LOAD(vkCmdDrawIndexedIndirect)
    LOAD(vkCmdDispatch)
    LOAD(vkCmdDispatchIndirect)
    LOAD(vkCmdCopyBuffer)
    LOAD(vkCmdCopyImage)
    LOAD(vkCmdBlitImage)
    LOAD(vkCmdCopyBufferToImage)
    LOAD(vkCmdCopyImageToBuffer)
    LOAD(vkCmdUpdateBuffer)
    LOAD(vkCmdFillBuffer)
    LOAD(vkCmdClearColorImage)
    LOAD(vkCmdClearDepthStencilImage)
    LOAD(vkCmdClearAttachments)
    LOAD(vkCmdResolveImage)
    LOAD(vkCmdSetEvent)
    LOAD(vkCmdResetEvent)
    LOAD(vkCmdWaitEvents)
    LOAD(vkCmdPipelineBarrier)
    LOAD(vkCmdBeginQuery)
    LOAD(vkCmdEndQuery)
    LOAD(vkCmdResetQueryPool)
    LOAD(vkCmdWriteTimestamp)
    LOAD(vkCmdCopyQueryPoolResults)
    LOAD(vkCmdPushConstants)
    LOAD(vkCmdBeginRenderPass)
    LOAD(vkCmdNextSubpass)
    LOAD(vkCmdEndRenderPass)
    LOAD(vkCmdExecuteCommands)
    LOAD(vkEnumerateInstanceVersion)
    LOAD(vkBindBufferMemory2)
    LOAD(vkBindImageMemory2)
    LOAD(vkGetDeviceGroupPeerMemoryFeatures)
    LOAD(vkCmdSetDeviceMask)
    LOAD(vkCmdDispatchBase)
    LOAD(vkEnumeratePhysicalDeviceGroups)
    LOAD(vkGetImageMemoryRequirements2)
    LOAD(vkGetBufferMemoryRequirements2)
    LOAD(vkGetImageSparseMemoryRequirements2)
    LOAD(vkGetPhysicalDeviceFeatures2)
    LOAD(vkGetPhysicalDeviceProperties2)
    LOAD(vkGetPhysicalDeviceFormatProperties2)
    LOAD(vkGetPhysicalDeviceImageFormatProperties2)
    LOAD(vkGetPhysicalDeviceQueueFamilyProperties2)
    LOAD(vkGetPhysicalDeviceMemoryProperties2)
    LOAD(vkGetPhysicalDeviceSparseImageFormatProperties2)
    LOAD(vkTrimCommandPool)
    LOAD(vkGetDeviceQueue2)
    LOAD(vkCreateSamplerYcbcrConversion)
    LOAD(vkDestroySamplerYcbcrConversion)
    LOAD(vkCreateDescriptorUpdateTemplate)
    LOAD(vkDestroyDescriptorUpdateTemplate)
    LOAD(vkUpdateDescriptorSetWithTemplate)
    LOAD(vkGetPhysicalDeviceExternalBufferProperties)
    LOAD(vkGetPhysicalDeviceExternalFenceProperties)
    LOAD(vkGetPhysicalDeviceExternalSemaphoreProperties)
    LOAD(vkGetDescriptorSetLayoutSupport)
    LOAD(vkCmdDrawIndirectCount)
    LOAD(vkCmdDrawIndexedIndirectCount)
    LOAD(vkCreateRenderPass2)
    LOAD(vkCmdBeginRenderPass2)
    LOAD(vkCmdNextSubpass2)
    LOAD(vkCmdEndRenderPass2)
    LOAD(vkResetQueryPool)
    LOAD(vkGetSemaphoreCounterValue)
    LOAD(vkWaitSemaphores)
    LOAD(vkSignalSemaphore)
    LOAD(vkGetBufferDeviceAddress)
    LOAD(vkGetBufferOpaqueCaptureAddress)
    LOAD(vkGetDeviceMemoryOpaqueCaptureAddress)
    LOAD(vkGetPhysicalDeviceToolProperties)
    LOAD(vkCreatePrivateDataSlot)
    LOAD(vkDestroyPrivateDataSlot)
    LOAD(vkSetPrivateData)
    LOAD(vkGetPrivateData)
    LOAD(vkCmdSetEvent2)
    LOAD(vkCmdResetEvent2)
    LOAD(vkCmdWaitEvents2)
    LOAD(vkCmdPipelineBarrier2)
    LOAD(vkCmdWriteTimestamp2)
    LOAD(vkQueueSubmit2)
    LOAD(vkCmdCopyBuffer2)
    LOAD(vkCmdCopyImage2)
    LOAD(vkCmdCopyBufferToImage2)
    LOAD(vkCmdCopyImageToBuffer2)
    LOAD(vkCmdBlitImage2)
    LOAD(vkCmdResolveImage2)
    LOAD(vkCmdBeginRendering)
    LOAD(vkCmdEndRendering)
    LOAD(vkCmdSetCullMode)
    LOAD(vkCmdSetFrontFace)
    LOAD(vkCmdSetPrimitiveTopology)
    LOAD(vkCmdSetViewportWithCount)
    LOAD(vkCmdSetScissorWithCount)
    LOAD(vkCmdBindVertexBuffers2)
    LOAD(vkCmdSetDepthTestEnable)
    LOAD(vkCmdSetDepthWriteEnable)
    LOAD(vkCmdSetDepthCompareOp)
    LOAD(vkCmdSetDepthBoundsTestEnable)
    LOAD(vkCmdSetStencilTestEnable)
    LOAD(vkCmdSetStencilOp)
    LOAD(vkCmdSetRasterizerDiscardEnable)
    LOAD(vkCmdSetDepthBiasEnable)
    LOAD(vkCmdSetPrimitiveRestartEnable)
    LOAD(vkGetDeviceBufferMemoryRequirements)
    LOAD(vkGetDeviceImageMemoryRequirements)
    LOAD(vkGetDeviceImageSparseMemoryRequirements)
    LOAD(vkCmdSetLineStipple)
    LOAD(vkMapMemory2)
    LOAD(vkUnmapMemory2)
    LOAD(vkCmdBindIndexBuffer2)
    LOAD(vkGetRenderingAreaGranularity)
    LOAD(vkGetDeviceImageSubresourceLayout)
    LOAD(vkGetImageSubresourceLayout2)
    LOAD(vkCmdPushDescriptorSet)
    LOAD(vkCmdPushDescriptorSetWithTemplate)
    LOAD(vkCmdSetRenderingAttachmentLocations)
    LOAD(vkCmdSetRenderingInputAttachmentIndices)
    LOAD(vkCmdBindDescriptorSets2)
    LOAD(vkCmdPushConstants2)
    LOAD(vkCmdPushDescriptorSet2)
    LOAD(vkCmdPushDescriptorSetWithTemplate2)
    LOAD(vkCopyMemoryToImage)
    LOAD(vkCopyImageToMemory)
    LOAD(vkCopyImageToImage)
    LOAD(vkTransitionImageLayout)
    LOAD(vkDestroySurfaceKHR)
    LOAD(vkGetPhysicalDeviceSurfaceSupportKHR)
    LOAD(vkGetPhysicalDeviceSurfaceCapabilitiesKHR)
    LOAD(vkGetPhysicalDeviceSurfaceFormatsKHR)
    LOAD(vkGetPhysicalDeviceSurfacePresentModesKHR)
    LOAD(vkCreateSwapchainKHR)
    LOAD(vkDestroySwapchainKHR)
    LOAD(vkGetSwapchainImagesKHR)
    LOAD(vkAcquireNextImageKHR)
    LOAD(vkQueuePresentKHR)
    LOAD(vkGetDeviceGroupPresentCapabilitiesKHR)
    LOAD(vkGetDeviceGroupSurfacePresentModesKHR)
    LOAD(vkGetPhysicalDevicePresentRectanglesKHR)
    LOAD(vkAcquireNextImage2KHR)
    LOAD(vkGetPhysicalDeviceDisplayPropertiesKHR)
    LOAD(vkGetPhysicalDeviceDisplayPlanePropertiesKHR)
    LOAD(vkGetDisplayPlaneSupportedDisplaysKHR)
    LOAD(vkGetDisplayModePropertiesKHR)
    LOAD(vkCreateDisplayModeKHR)
    LOAD(vkGetDisplayPlaneCapabilitiesKHR)
    LOAD(vkCreateDisplayPlaneSurfaceKHR)
    LOAD(vkCreateSharedSwapchainsKHR)
    LOAD(vkGetPhysicalDeviceVideoCapabilitiesKHR)
    LOAD(vkGetPhysicalDeviceVideoFormatPropertiesKHR)
    LOAD(vkCreateVideoSessionKHR)
    LOAD(vkDestroyVideoSessionKHR)
    LOAD(vkGetVideoSessionMemoryRequirementsKHR)
    LOAD(vkBindVideoSessionMemoryKHR)
    LOAD(vkCreateVideoSessionParametersKHR)
    LOAD(vkUpdateVideoSessionParametersKHR)
    LOAD(vkDestroyVideoSessionParametersKHR)
    LOAD(vkCmdBeginVideoCodingKHR)
    LOAD(vkCmdEndVideoCodingKHR)
    LOAD(vkCmdControlVideoCodingKHR)
    LOAD(vkCmdDecodeVideoKHR)
    LOAD(vkCmdBeginRenderingKHR)
    LOAD(vkCmdEndRenderingKHR)
    LOAD(vkGetPhysicalDeviceFeatures2KHR)
    LOAD(vkGetPhysicalDeviceProperties2KHR)
    LOAD(vkGetPhysicalDeviceFormatProperties2KHR)
    LOAD(vkGetPhysicalDeviceImageFormatProperties2KHR)
    LOAD(vkGetPhysicalDeviceQueueFamilyProperties2KHR)
    LOAD(vkGetPhysicalDeviceMemoryProperties2KHR)
    LOAD(vkGetPhysicalDeviceSparseImageFormatProperties2KHR)
    LOAD(vkGetDeviceGroupPeerMemoryFeaturesKHR)
    LOAD(vkCmdSetDeviceMaskKHR)
    LOAD(vkCmdDispatchBaseKHR)
    LOAD(vkTrimCommandPoolKHR)
    LOAD(vkEnumeratePhysicalDeviceGroupsKHR)
    LOAD(vkGetPhysicalDeviceExternalBufferPropertiesKHR)
    LOAD(vkGetMemoryFdKHR)
    LOAD(vkGetMemoryFdPropertiesKHR)
    LOAD(vkGetPhysicalDeviceExternalSemaphorePropertiesKHR)
    LOAD(vkImportSemaphoreFdKHR)
    LOAD(vkGetSemaphoreFdKHR)
    LOAD(vkCmdPushDescriptorSetKHR)
    LOAD(vkCmdPushDescriptorSetWithTemplateKHR)
    LOAD(vkCreateDescriptorUpdateTemplateKHR)
    LOAD(vkDestroyDescriptorUpdateTemplateKHR)
    LOAD(vkUpdateDescriptorSetWithTemplateKHR)
    LOAD(vkCreateRenderPass2KHR)
    LOAD(vkCmdBeginRenderPass2KHR)
    LOAD(vkCmdNextSubpass2KHR)
    LOAD(vkCmdEndRenderPass2KHR)
    LOAD(vkGetSwapchainStatusKHR)
    LOAD(vkGetPhysicalDeviceExternalFencePropertiesKHR)
    LOAD(vkImportFenceFdKHR)
    LOAD(vkGetFenceFdKHR)
    LOAD(vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR)
    LOAD(vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR)
    LOAD(vkAcquireProfilingLockKHR)
    LOAD(vkReleaseProfilingLockKHR)
    LOAD(vkGetPhysicalDeviceSurfaceCapabilities2KHR)
    LOAD(vkGetPhysicalDeviceSurfaceFormats2KHR)
    LOAD(vkGetPhysicalDeviceDisplayProperties2KHR)
    LOAD(vkGetPhysicalDeviceDisplayPlaneProperties2KHR)
    LOAD(vkGetDisplayModeProperties2KHR)
    LOAD(vkGetDisplayPlaneCapabilities2KHR)
    LOAD(vkGetImageMemoryRequirements2KHR)
    LOAD(vkGetBufferMemoryRequirements2KHR)
    LOAD(vkGetImageSparseMemoryRequirements2KHR)
    LOAD(vkCreateSamplerYcbcrConversionKHR)
    LOAD(vkDestroySamplerYcbcrConversionKHR)
    LOAD(vkBindBufferMemory2KHR)
    LOAD(vkBindImageMemory2KHR)
    LOAD(vkGetDescriptorSetLayoutSupportKHR)
    LOAD(vkCmdDrawIndirectCountKHR)
    LOAD(vkCmdDrawIndexedIndirectCountKHR)
    LOAD(vkGetSemaphoreCounterValueKHR)
    LOAD(vkWaitSemaphoresKHR)
    LOAD(vkSignalSemaphoreKHR)
    LOAD(vkGetPhysicalDeviceFragmentShadingRatesKHR)
    LOAD(vkCmdSetFragmentShadingRateKHR)
    LOAD(vkCmdSetRenderingAttachmentLocationsKHR)
    LOAD(vkCmdSetRenderingInputAttachmentIndicesKHR)
    LOAD(vkWaitForPresentKHR)
    LOAD(vkGetBufferDeviceAddressKHR)
    LOAD(vkGetBufferOpaqueCaptureAddressKHR)
    LOAD(vkGetDeviceMemoryOpaqueCaptureAddressKHR)
    LOAD(vkCreateDeferredOperationKHR)
    LOAD(vkDestroyDeferredOperationKHR)
    LOAD(vkGetDeferredOperationMaxConcurrencyKHR)
    LOAD(vkGetDeferredOperationResultKHR)
    LOAD(vkDeferredOperationJoinKHR)
    LOAD(vkGetPipelineExecutablePropertiesKHR)
    LOAD(vkGetPipelineExecutableStatisticsKHR)
    LOAD(vkGetPipelineExecutableInternalRepresentationsKHR)
    LOAD(vkMapMemory2KHR)
    LOAD(vkUnmapMemory2KHR)
    LOAD(vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR)
    LOAD(vkGetEncodedVideoSessionParametersKHR)
    LOAD(vkCmdEncodeVideoKHR)
    LOAD(vkCmdSetEvent2KHR)
    LOAD(vkCmdResetEvent2KHR)
    LOAD(vkCmdWaitEvents2KHR)
    LOAD(vkCmdPipelineBarrier2KHR)
    LOAD(vkCmdWriteTimestamp2KHR)
    LOAD(vkQueueSubmit2KHR)
    LOAD(vkCmdCopyBuffer2KHR)
    LOAD(vkCmdCopyImage2KHR)
    LOAD(vkCmdCopyBufferToImage2KHR)
    LOAD(vkCmdCopyImageToBuffer2KHR)
    LOAD(vkCmdBlitImage2KHR)
    LOAD(vkCmdResolveImage2KHR)
    LOAD(vkCmdTraceRaysIndirect2KHR)
    LOAD(vkGetDeviceBufferMemoryRequirementsKHR)
    LOAD(vkGetDeviceImageMemoryRequirementsKHR)
    LOAD(vkGetDeviceImageSparseMemoryRequirementsKHR)
    LOAD(vkCmdBindIndexBuffer2KHR)
    LOAD(vkGetRenderingAreaGranularityKHR)
    LOAD(vkGetDeviceImageSubresourceLayoutKHR)
    LOAD(vkGetImageSubresourceLayout2KHR)
    LOAD(vkCreatePipelineBinariesKHR)
    LOAD(vkDestroyPipelineBinaryKHR)
    LOAD(vkGetPipelineKeyKHR)
    LOAD(vkGetPipelineBinaryDataKHR)
    LOAD(vkReleaseCapturedPipelineDataKHR)
    LOAD(vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR)
    LOAD(vkCmdSetLineStippleKHR)
    LOAD(vkGetPhysicalDeviceCalibrateableTimeDomainsKHR)
    LOAD(vkGetCalibratedTimestampsKHR)
    LOAD(vkCmdBindDescriptorSets2KHR)
    LOAD(vkCmdPushConstants2KHR)
    LOAD(vkCmdPushDescriptorSet2KHR)
    LOAD(vkCmdPushDescriptorSetWithTemplate2KHR)
    LOAD(vkCmdSetDescriptorBufferOffsets2EXT)
    LOAD(vkCmdBindDescriptorBufferEmbeddedSamplers2EXT)
    LOAD(vkCreateAccelerationStructureKHR)
    LOAD(vkDestroyAccelerationStructureKHR)
    LOAD(vkCmdBuildAccelerationStructuresKHR)
    LOAD(vkCmdBuildAccelerationStructuresIndirectKHR)
    LOAD(vkBuildAccelerationStructuresKHR)
    LOAD(vkCopyAccelerationStructureKHR)
    LOAD(vkCopyAccelerationStructureToMemoryKHR)
    LOAD(vkCopyMemoryToAccelerationStructureKHR)
    LOAD(vkWriteAccelerationStructuresPropertiesKHR)
    LOAD(vkCmdCopyAccelerationStructureKHR)
    LOAD(vkCmdCopyAccelerationStructureToMemoryKHR)
    LOAD(vkCmdCopyMemoryToAccelerationStructureKHR)
    LOAD(vkGetAccelerationStructureDeviceAddressKHR)
    LOAD(vkCmdWriteAccelerationStructuresPropertiesKHR)
    LOAD(vkGetDeviceAccelerationStructureCompatibilityKHR)
    LOAD(vkGetAccelerationStructureBuildSizesKHR)
    LOAD(vkCmdTraceRaysKHR)
    LOAD(vkCreateRayTracingPipelinesKHR)
    LOAD(vkGetRayTracingCaptureReplayShaderGroupHandlesKHR)
    LOAD(vkCmdTraceRaysIndirectKHR)
    LOAD(vkGetRayTracingShaderGroupStackSizeKHR)
    LOAD(vkCmdSetRayTracingPipelineStackSizeKHR)

#ifdef VK_USE_PLATFORM_ANDROID_KHR
    LOAD(vkCreateAndroidSurfaceKHR)
#endif

#ifdef VK_USE_PLATFORM_WAYLAND_KHR
    LOAD(vkCreateWaylandSurfaceKHR)
    LOAD(vkGetPhysicalDeviceWaylandPresentationSupportKHR)
#endif

#ifdef VK_USE_PLATFORM_WIN32_KHR
    LOAD(vkCreateWin32SurfaceKHR)
    LOAD(vkGetPhysicalDeviceWin32PresentationSupportKHR)
    LOAD(vkGetMemoryWin32HandleKHR)
    LOAD(vkGetMemoryWin32HandlePropertiesKHR)
    LOAD(vkImportSemaphoreWin32HandleKHR)
    LOAD(vkGetSemaphoreWin32HandleKHR)
    LOAD(vkImportFenceWin32HandleKHR)
    LOAD(vkGetFenceWin32HandleKHR)
#endif

#ifdef VK_USE_PLATFORM_XCB_KHR
    LOAD(vkCreateXcbSurfaceKHR)
    LOAD(vkGetPhysicalDeviceXcbPresentationSupportKHR)
#endif

#ifdef VK_USE_PLATFORM_XLIB_KHR
    LOAD(vkCreateXlibSurfaceKHR)
    LOAD(vkGetPhysicalDeviceXlibPresentationSupportKHR)
#endif
#undef LOAD
return true;
}


// Set Vulkan function pointers to use a specific device.
void vexLoadDevice(VkDevice device) {
#define LOAD_DEVICE(PROC) PROC = (PFN_##PROC) vkGetDeviceProcAddr(device, #PROC);
    LOAD_DEVICE(vkGetDeviceProcAddr)
    LOAD_DEVICE(vkDestroyDevice)
    LOAD_DEVICE(vkGetDeviceQueue)
    LOAD_DEVICE(vkQueueSubmit)
    LOAD_DEVICE(vkQueueWaitIdle)
    LOAD_DEVICE(vkDeviceWaitIdle)
    LOAD_DEVICE(vkAllocateMemory)
    LOAD_DEVICE(vkFreeMemory)
    LOAD_DEVICE(vkMapMemory)
    LOAD_DEVICE(vkUnmapMemory)
    LOAD_DEVICE(vkFlushMappedMemoryRanges)
    LOAD_DEVICE(vkInvalidateMappedMemoryRanges)
    LOAD_DEVICE(vkGetDeviceMemoryCommitment)
    LOAD_DEVICE(vkBindBufferMemory)
    LOAD_DEVICE(vkBindImageMemory)
    LOAD_DEVICE(vkGetBufferMemoryRequirements)
    LOAD_DEVICE(vkGetImageMemoryRequirements)
    LOAD_DEVICE(vkGetImageSparseMemoryRequirements)
    LOAD_DEVICE(vkQueueBindSparse)
    LOAD_DEVICE(vkCreateFence)
    LOAD_DEVICE(vkDestroyFence)
    LOAD_DEVICE(vkResetFences)
    LOAD_DEVICE(vkGetFenceStatus)
    LOAD_DEVICE(vkWaitForFences)
    LOAD_DEVICE(vkCreateSemaphore)
    LOAD_DEVICE(vkDestroySemaphore)
    LOAD_DEVICE(vkCreateEvent)
    LOAD_DEVICE(vkDestroyEvent)
    LOAD_DEVICE(vkGetEventStatus)
    LOAD_DEVICE(vkSetEvent)
    LOAD_DEVICE(vkResetEvent)
    LOAD_DEVICE(vkCreateQueryPool)
    LOAD_DEVICE(vkDestroyQueryPool)
    LOAD_DEVICE(vkGetQueryPoolResults)
    LOAD_DEVICE(vkCreateBuffer)
    LOAD_DEVICE(vkDestroyBuffer)
    LOAD_DEVICE(vkCreateBufferView)
    LOAD_DEVICE(vkDestroyBufferView)
    LOAD_DEVICE(vkCreateImage)
    LOAD_DEVICE(vkDestroyImage)
    LOAD_DEVICE(vkGetImageSubresourceLayout)
    LOAD_DEVICE(vkCreateImageView)
    LOAD_DEVICE(vkDestroyImageView)
    LOAD_DEVICE(vkCreateShaderModule)
    LOAD_DEVICE(vkDestroyShaderModule)
    LOAD_DEVICE(vkCreatePipelineCache)
    LOAD_DEVICE(vkDestroyPipelineCache)
    LOAD_DEVICE(vkGetPipelineCacheData)
    LOAD_DEVICE(vkMergePipelineCaches)
    LOAD_DEVICE(vkCreateGraphicsPipelines)
    LOAD_DEVICE(vkCreateComputePipelines)
    LOAD_DEVICE(vkDestroyPipeline)
    LOAD_DEVICE(vkCreatePipelineLayout)
    LOAD_DEVICE(vkDestroyPipelineLayout)
    LOAD_DEVICE(vkCreateSampler)
    LOAD_DEVICE(vkDestroySampler)
    LOAD_DEVICE(vkCreateDescriptorSetLayout)
    LOAD_DEVICE(vkDestroyDescriptorSetLayout)
    LOAD_DEVICE(vkCreateDescriptorPool)
    LOAD_DEVICE(vkDestroyDescriptorPool)
    LOAD_DEVICE(vkResetDescriptorPool)
    LOAD_DEVICE(vkAllocateDescriptorSets)
    LOAD_DEVICE(vkFreeDescriptorSets)
    LOAD_DEVICE(vkUpdateDescriptorSets)
    LOAD_DEVICE(vkCreateFramebuffer)
    LOAD_DEVICE(vkDestroyFramebuffer)
    LOAD_DEVICE(vkCreateRenderPass)
    LOAD_DEVICE(vkDestroyRenderPass)
    LOAD_DEVICE(vkGetRenderAreaGranularity)
    LOAD_DEVICE(vkCreateCommandPool)
    LOAD_DEVICE(vkDestroyCommandPool)
    LOAD_DEVICE(vkResetCommandPool)
    LOAD_DEVICE(vkAllocateCommandBuffers)
    LOAD_DEVICE(vkFreeCommandBuffers)
    LOAD_DEVICE(vkBeginCommandBuffer)
    LOAD_DEVICE(vkEndCommandBuffer)
    LOAD_DEVICE(vkResetCommandBuffer)
    LOAD_DEVICE(vkCmdBindPipeline)
    LOAD_DEVICE(vkCmdSetViewport)
    LOAD_DEVICE(vkCmdSetScissor)
    LOAD_DEVICE(vkCmdSetLineWidth)
    LOAD_DEVICE(vkCmdSetDepthBias)
    LOAD_DEVICE(vkCmdSetBlendConstants)
    LOAD_DEVICE(vkCmdSetDepthBounds)
    LOAD_DEVICE(vkCmdSetStencilCompareMask)
    LOAD_DEVICE(vkCmdSetStencilWriteMask)
    LOAD_DEVICE(vkCmdSetStencilReference)
    LOAD_DEVICE(vkCmdBindDescriptorSets)
    LOAD_DEVICE(vkCmdBindIndexBuffer)
    LOAD_DEVICE(vkCmdBindVertexBuffers)
    LOAD_DEVICE(vkCmdDraw)
    LOAD_DEVICE(vkCmdDrawIndexed)
    LOAD_DEVICE(vkCmdDrawIndirect)
    LOAD_DEVICE(vkCmdDrawIndexedIndirect)
    LOAD_DEVICE(vkCmdDispatch)
    LOAD_DEVICE(vkCmdDispatchIndirect)
    LOAD_DEVICE(vkCmdCopyBuffer)
    LOAD_DEVICE(vkCmdCopyImage)
    LOAD_DEVICE(vkCmdBlitImage)
    LOAD_DEVICE(vkCmdCopyBufferToImage)
    LOAD_DEVICE(vkCmdCopyImageToBuffer)
    LOAD_DEVICE(vkCmdUpdateBuffer)
    LOAD_DEVICE(vkCmdFillBuffer)
    LOAD_DEVICE(vkCmdClearColorImage)
    LOAD_DEVICE(vkCmdClearDepthStencilImage)
    LOAD_DEVICE(vkCmdClearAttachments)
    LOAD_DEVICE(vkCmdResolveImage)
    LOAD_DEVICE(vkCmdSetEvent)
    LOAD_DEVICE(vkCmdResetEvent)
    LOAD_DEVICE(vkCmdWaitEvents)
    LOAD_DEVICE(vkCmdPipelineBarrier)
    LOAD_DEVICE(vkCmdBeginQuery)
    LOAD_DEVICE(vkCmdEndQuery)
    LOAD_DEVICE(vkCmdResetQueryPool)
    LOAD_DEVICE(vkCmdWriteTimestamp)
    LOAD_DEVICE(vkCmdCopyQueryPoolResults)
    LOAD_DEVICE(vkCmdPushConstants)
    LOAD_DEVICE(vkCmdBeginRenderPass)
    LOAD_DEVICE(vkCmdNextSubpass)
    LOAD_DEVICE(vkCmdEndRenderPass)
    LOAD_DEVICE(vkCmdExecuteCommands)
    LOAD_DEVICE(vkBindBufferMemory2)
    LOAD_DEVICE(vkBindImageMemory2)
    LOAD_DEVICE(vkGetDeviceGroupPeerMemoryFeatures)
    LOAD_DEVICE(vkCmdSetDeviceMask)
    LOAD_DEVICE(vkCmdDispatchBase)
    LOAD_DEVICE(vkGetImageMemoryRequirements2)
    LOAD_DEVICE(vkGetBufferMemoryRequirements2)
    LOAD_DEVICE(vkGetImageSparseMemoryRequirements2)
    LOAD_DEVICE(vkTrimCommandPool)
    LOAD_DEVICE(vkGetDeviceQueue2)
    LOAD_DEVICE(vkCreateSamplerYcbcrConversion)
    LOAD_DEVICE(vkDestroySamplerYcbcrConversion)
    LOAD_DEVICE(vkCreateDescriptorUpdateTemplate)
    LOAD_DEVICE(vkDestroyDescriptorUpdateTemplate)
    LOAD_DEVICE(vkUpdateDescriptorSetWithTemplate)
    LOAD_DEVICE(vkGetDescriptorSetLayoutSupport)
    LOAD_DEVICE(vkCmdDrawIndirectCount)
    LOAD_DEVICE(vkCmdDrawIndexedIndirectCount)
    LOAD_DEVICE(vkCreateRenderPass2)
    LOAD_DEVICE(vkCmdBeginRenderPass2)
    LOAD_DEVICE(vkCmdNextSubpass2)
    LOAD_DEVICE(vkCmdEndRenderPass2)
    LOAD_DEVICE(vkResetQueryPool)
    LOAD_DEVICE(vkGetSemaphoreCounterValue)
    LOAD_DEVICE(vkWaitSemaphores)
    LOAD_DEVICE(vkSignalSemaphore)
    LOAD_DEVICE(vkGetBufferDeviceAddress)
    LOAD_DEVICE(vkGetBufferOpaqueCaptureAddress)
    LOAD_DEVICE(vkGetDeviceMemoryOpaqueCaptureAddress)
    LOAD_DEVICE(vkCreatePrivateDataSlot)
    LOAD_DEVICE(vkDestroyPrivateDataSlot)
    LOAD_DEVICE(vkSetPrivateData)
    LOAD_DEVICE(vkGetPrivateData)
    LOAD_DEVICE(vkCmdSetEvent2)
    LOAD_DEVICE(vkCmdResetEvent2)
    LOAD_DEVICE(vkCmdWaitEvents2)
    LOAD_DEVICE(vkCmdPipelineBarrier2)
    LOAD_DEVICE(vkCmdWriteTimestamp2)
    LOAD_DEVICE(vkQueueSubmit2)
    LOAD_DEVICE(vkCmdCopyBuffer2)
    LOAD_DEVICE(vkCmdCopyImage2)
    LOAD_DEVICE(vkCmdCopyBufferToImage2)
    LOAD_DEVICE(vkCmdCopyImageToBuffer2)
    LOAD_DEVICE(vkCmdBlitImage2)
    LOAD_DEVICE(vkCmdResolveImage2)
    LOAD_DEVICE(vkCmdBeginRendering)
    LOAD_DEVICE(vkCmdEndRendering)
    LOAD_DEVICE(vkCmdSetCullMode)
    LOAD_DEVICE(vkCmdSetFrontFace)
    LOAD_DEVICE(vkCmdSetPrimitiveTopology)
    LOAD_DEVICE(vkCmdSetViewportWithCount)
    LOAD_DEVICE(vkCmdSetScissorWithCount)
    LOAD_DEVICE(vkCmdBindVertexBuffers2)
    LOAD_DEVICE(vkCmdSetDepthTestEnable)
    LOAD_DEVICE(vkCmdSetDepthWriteEnable)
    LOAD_DEVICE(vkCmdSetDepthCompareOp)
    LOAD_DEVICE(vkCmdSetDepthBoundsTestEnable)
    LOAD_DEVICE(vkCmdSetStencilTestEnable)
    LOAD_DEVICE(vkCmdSetStencilOp)
    LOAD_DEVICE(vkCmdSetRasterizerDiscardEnable)
    LOAD_DEVICE(vkCmdSetDepthBiasEnable)
    LOAD_DEVICE(vkCmdSetPrimitiveRestartEnable)
    LOAD_DEVICE(vkGetDeviceBufferMemoryRequirements)
    LOAD_DEVICE(vkGetDeviceImageMemoryRequirements)
    LOAD_DEVICE(vkGetDeviceImageSparseMemoryRequirements)
    LOAD_DEVICE(vkCmdSetLineStipple)
    LOAD_DEVICE(vkMapMemory2)
    LOAD_DEVICE(vkUnmapMemory2)
    LOAD_DEVICE(vkCmdBindIndexBuffer2)
    LOAD_DEVICE(vkGetRenderingAreaGranularity)
    LOAD_DEVICE(vkGetDeviceImageSubresourceLayout)
    LOAD_DEVICE(vkGetImageSubresourceLayout2)
    LOAD_DEVICE(vkCmdPushDescriptorSet)
    LOAD_DEVICE(vkCmdPushDescriptorSetWithTemplate)
    LOAD_DEVICE(vkCmdSetRenderingAttachmentLocations)
    LOAD_DEVICE(vkCmdSetRenderingInputAttachmentIndices)
    LOAD_DEVICE(vkCmdBindDescriptorSets2)
    LOAD_DEVICE(vkCmdPushConstants2)
    LOAD_DEVICE(vkCmdPushDescriptorSet2)
    LOAD_DEVICE(vkCmdPushDescriptorSetWithTemplate2)
    LOAD_DEVICE(vkCopyMemoryToImage)
    LOAD_DEVICE(vkCopyImageToMemory)
    LOAD_DEVICE(vkCopyImageToImage)
    LOAD_DEVICE(vkTransitionImageLayout)
    LOAD_DEVICE(vkCreateSwapchainKHR)
    LOAD_DEVICE(vkDestroySwapchainKHR)
    LOAD_DEVICE(vkGetSwapchainImagesKHR)
    LOAD_DEVICE(vkAcquireNextImageKHR)
    LOAD_DEVICE(vkQueuePresentKHR)
    LOAD_DEVICE(vkGetDeviceGroupPresentCapabilitiesKHR)
    LOAD_DEVICE(vkGetDeviceGroupSurfacePresentModesKHR)
    LOAD_DEVICE(vkAcquireNextImage2KHR)
    LOAD_DEVICE(vkCreateSharedSwapchainsKHR)
    LOAD_DEVICE(vkCreateVideoSessionKHR)
    LOAD_DEVICE(vkDestroyVideoSessionKHR)
    LOAD_DEVICE(vkGetVideoSessionMemoryRequirementsKHR)
    LOAD_DEVICE(vkBindVideoSessionMemoryKHR)
    LOAD_DEVICE(vkCreateVideoSessionParametersKHR)
    LOAD_DEVICE(vkUpdateVideoSessionParametersKHR)
    LOAD_DEVICE(vkDestroyVideoSessionParametersKHR)
    LOAD_DEVICE(vkCmdBeginVideoCodingKHR)
    LOAD_DEVICE(vkCmdEndVideoCodingKHR)
    LOAD_DEVICE(vkCmdControlVideoCodingKHR)
    LOAD_DEVICE(vkCmdDecodeVideoKHR)
    LOAD_DEVICE(vkCmdBeginRenderingKHR)
    LOAD_DEVICE(vkCmdEndRenderingKHR)
    LOAD_DEVICE(vkGetDeviceGroupPeerMemoryFeaturesKHR)
    LOAD_DEVICE(vkCmdSetDeviceMaskKHR)
    LOAD_DEVICE(vkCmdDispatchBaseKHR)
    LOAD_DEVICE(vkTrimCommandPoolKHR)
    LOAD_DEVICE(vkGetMemoryFdKHR)
    LOAD_DEVICE(vkGetMemoryFdPropertiesKHR)
    LOAD_DEVICE(vkImportSemaphoreFdKHR)
    LOAD_DEVICE(vkGetSemaphoreFdKHR)
    LOAD_DEVICE(vkCmdPushDescriptorSetKHR)
    LOAD_DEVICE(vkCmdPushDescriptorSetWithTemplateKHR)
    LOAD_DEVICE(vkCreateDescriptorUpdateTemplateKHR)
    LOAD_DEVICE(vkDestroyDescriptorUpdateTemplateKHR)
    LOAD_DEVICE(vkUpdateDescriptorSetWithTemplateKHR)
    LOAD_DEVICE(vkCreateRenderPass2KHR)
    LOAD_DEVICE(vkCmdBeginRenderPass2KHR)
    LOAD_DEVICE(vkCmdNextSubpass2KHR)
    LOAD_DEVICE(vkCmdEndRenderPass2KHR)
    LOAD_DEVICE(vkGetSwapchainStatusKHR)
    LOAD_DEVICE(vkImportFenceFdKHR)
    LOAD_DEVICE(vkGetFenceFdKHR)
    LOAD_DEVICE(vkAcquireProfilingLockKHR)
    LOAD_DEVICE(vkReleaseProfilingLockKHR)
    LOAD_DEVICE(vkGetImageMemoryRequirements2KHR)
    LOAD_DEVICE(vkGetBufferMemoryRequirements2KHR)
    LOAD_DEVICE(vkGetImageSparseMemoryRequirements2KHR)
    LOAD_DEVICE(vkCreateSamplerYcbcrConversionKHR)
    LOAD_DEVICE(vkDestroySamplerYcbcrConversionKHR)
    LOAD_DEVICE(vkBindBufferMemory2KHR)
    LOAD_DEVICE(vkBindImageMemory2KHR)
    LOAD_DEVICE(vkGetDescriptorSetLayoutSupportKHR)
    LOAD_DEVICE(vkCmdDrawIndirectCountKHR)
    LOAD_DEVICE(vkCmdDrawIndexedIndirectCountKHR)
    LOAD_DEVICE(vkGetSemaphoreCounterValueKHR)
    LOAD_DEVICE(vkWaitSemaphoresKHR)
    LOAD_DEVICE(vkSignalSemaphoreKHR)
    LOAD_DEVICE(vkCmdSetFragmentShadingRateKHR)
    LOAD_DEVICE(vkCmdSetRenderingAttachmentLocationsKHR)
    LOAD_DEVICE(vkCmdSetRenderingInputAttachmentIndicesKHR)
    LOAD_DEVICE(vkWaitForPresentKHR)
    LOAD_DEVICE(vkGetBufferDeviceAddressKHR)
    LOAD_DEVICE(vkGetBufferOpaqueCaptureAddressKHR)
    LOAD_DEVICE(vkGetDeviceMemoryOpaqueCaptureAddressKHR)
    LOAD_DEVICE(vkCreateDeferredOperationKHR)
    LOAD_DEVICE(vkDestroyDeferredOperationKHR)
    LOAD_DEVICE(vkGetDeferredOperationMaxConcurrencyKHR)
    LOAD_DEVICE(vkGetDeferredOperationResultKHR)
    LOAD_DEVICE(vkDeferredOperationJoinKHR)
    LOAD_DEVICE(vkGetPipelineExecutablePropertiesKHR)
    LOAD_DEVICE(vkGetPipelineExecutableStatisticsKHR)
    LOAD_DEVICE(vkGetPipelineExecutableInternalRepresentationsKHR)
    LOAD_DEVICE(vkMapMemory2KHR)
    LOAD_DEVICE(vkUnmapMemory2KHR)
    LOAD_DEVICE(vkGetEncodedVideoSessionParametersKHR)
    LOAD_DEVICE(vkCmdEncodeVideoKHR)
    LOAD_DEVICE(vkCmdSetEvent2KHR)
    LOAD_DEVICE(vkCmdResetEvent2KHR)
    LOAD_DEVICE(vkCmdWaitEvents2KHR)
    LOAD_DEVICE(vkCmdPipelineBarrier2KHR)
    LOAD_DEVICE(vkCmdWriteTimestamp2KHR)
    LOAD_DEVICE(vkQueueSubmit2KHR)
    LOAD_DEVICE(vkCmdCopyBuffer2KHR)
    LOAD_DEVICE(vkCmdCopyImage2KHR)
    LOAD_DEVICE(vkCmdCopyBufferToImage2KHR)
    LOAD_DEVICE(vkCmdCopyImageToBuffer2KHR)
    LOAD_DEVICE(vkCmdBlitImage2KHR)
    LOAD_DEVICE(vkCmdResolveImage2KHR)
    LOAD_DEVICE(vkCmdTraceRaysIndirect2KHR)
    LOAD_DEVICE(vkGetDeviceBufferMemoryRequirementsKHR)
    LOAD_DEVICE(vkGetDeviceImageMemoryRequirementsKHR)
    LOAD_DEVICE(vkGetDeviceImageSparseMemoryRequirementsKHR)
    LOAD_DEVICE(vkCmdBindIndexBuffer2KHR)
    LOAD_DEVICE(vkGetRenderingAreaGranularityKHR)
    LOAD_DEVICE(vkGetDeviceImageSubresourceLayoutKHR)
    LOAD_DEVICE(vkGetImageSubresourceLayout2KHR)
    LOAD_DEVICE(vkCreatePipelineBinariesKHR)
    LOAD_DEVICE(vkDestroyPipelineBinaryKHR)
    LOAD_DEVICE(vkGetPipelineKeyKHR)
    LOAD_DEVICE(vkGetPipelineBinaryDataKHR)
    LOAD_DEVICE(vkReleaseCapturedPipelineDataKHR)
    LOAD_DEVICE(vkCmdSetLineStippleKHR)
    LOAD_DEVICE(vkGetCalibratedTimestampsKHR)
    LOAD_DEVICE(vkCmdBindDescriptorSets2KHR)
    LOAD_DEVICE(vkCmdPushConstants2KHR)
    LOAD_DEVICE(vkCmdPushDescriptorSet2KHR)
    LOAD_DEVICE(vkCmdPushDescriptorSetWithTemplate2KHR)
    LOAD_DEVICE(vkCmdSetDescriptorBufferOffsets2EXT)
    LOAD_DEVICE(vkCmdBindDescriptorBufferEmbeddedSamplers2EXT)
    LOAD_DEVICE(vkCreateAccelerationStructureKHR)
    LOAD_DEVICE(vkDestroyAccelerationStructureKHR)
    LOAD_DEVICE(vkCmdBuildAccelerationStructuresKHR)
    LOAD_DEVICE(vkCmdBuildAccelerationStructuresIndirectKHR)
    LOAD_DEVICE(vkBuildAccelerationStructuresKHR)
    LOAD_DEVICE(vkCopyAccelerationStructureKHR)
    LOAD_DEVICE(vkCopyAccelerationStructureToMemoryKHR)
    LOAD_DEVICE(vkCopyMemoryToAccelerationStructureKHR)
    LOAD_DEVICE(vkWriteAccelerationStructuresPropertiesKHR)
    LOAD_DEVICE(vkCmdCopyAccelerationStructureKHR)
    LOAD_DEVICE(vkCmdCopyAccelerationStructureToMemoryKHR)
    LOAD_DEVICE(vkCmdCopyMemoryToAccelerationStructureKHR)
    LOAD_DEVICE(vkGetAccelerationStructureDeviceAddressKHR)
    LOAD_DEVICE(vkCmdWriteAccelerationStructuresPropertiesKHR)
    LOAD_DEVICE(vkGetDeviceAccelerationStructureCompatibilityKHR)
    LOAD_DEVICE(vkGetAccelerationStructureBuildSizesKHR)
    LOAD_DEVICE(vkCmdTraceRaysKHR)
    LOAD_DEVICE(vkCreateRayTracingPipelinesKHR)
    LOAD_DEVICE(vkGetRayTracingCaptureReplayShaderGroupHandlesKHR)
    LOAD_DEVICE(vkCmdTraceRaysIndirectKHR)
    LOAD_DEVICE(vkGetRayTracingShaderGroupStackSizeKHR)
    LOAD_DEVICE(vkCmdSetRayTracingPipelineStackSizeKHR)
#undef LOAD_DEVICE
}


PFN_vkCreateInstance vkCreateInstance;
PFN_vkDestroyInstance vkDestroyInstance;
PFN_vkEnumeratePhysicalDevices vkEnumeratePhysicalDevices;
PFN_vkGetPhysicalDeviceFeatures vkGetPhysicalDeviceFeatures;
PFN_vkGetPhysicalDeviceFormatProperties vkGetPhysicalDeviceFormatProperties;
PFN_vkGetPhysicalDeviceImageFormatProperties vkGetPhysicalDeviceImageFormatProperties;
PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties;
PFN_vkGetPhysicalDeviceQueueFamilyProperties vkGetPhysicalDeviceQueueFamilyProperties;
PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties;
PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr;
PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr;
PFN_vkCreateDevice vkCreateDevice;
PFN_vkDestroyDevice vkDestroyDevice;
PFN_vkEnumerateInstanceExtensionProperties vkEnumerateInstanceExtensionProperties;
PFN_vkEnumerateDeviceExtensionProperties vkEnumerateDeviceExtensionProperties;
PFN_vkEnumerateInstanceLayerProperties vkEnumerateInstanceLayerProperties;
PFN_vkEnumerateDeviceLayerProperties vkEnumerateDeviceLayerProperties;
PFN_vkGetDeviceQueue vkGetDeviceQueue;
PFN_vkQueueSubmit vkQueueSubmit;
PFN_vkQueueWaitIdle vkQueueWaitIdle;
PFN_vkDeviceWaitIdle vkDeviceWaitIdle;
PFN_vkAllocateMemory vkAllocateMemory;
PFN_vkFreeMemory vkFreeMemory;
PFN_vkMapMemory vkMapMemory;
PFN_vkUnmapMemory vkUnmapMemory;
PFN_vkFlushMappedMemoryRanges vkFlushMappedMemoryRanges;
PFN_vkInvalidateMappedMemoryRanges vkInvalidateMappedMemoryRanges;
PFN_vkGetDeviceMemoryCommitment vkGetDeviceMemoryCommitment;
PFN_vkBindBufferMemory vkBindBufferMemory;
PFN_vkBindImageMemory vkBindImageMemory;
PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements;
PFN_vkGetImageMemoryRequirements vkGetImageMemoryRequirements;
PFN_vkGetImageSparseMemoryRequirements vkGetImageSparseMemoryRequirements;
PFN_vkGetPhysicalDeviceSparseImageFormatProperties vkGetPhysicalDeviceSparseImageFormatProperties;
PFN_vkQueueBindSparse vkQueueBindSparse;
PFN_vkCreateFence vkCreateFence;
PFN_vkDestroyFence vkDestroyFence;
PFN_vkResetFences vkResetFences;
PFN_vkGetFenceStatus vkGetFenceStatus;
PFN_vkWaitForFences vkWaitForFences;
PFN_vkCreateSemaphore vkCreateSemaphore;
PFN_vkDestroySemaphore vkDestroySemaphore;
PFN_vkCreateEvent vkCreateEvent;
PFN_vkDestroyEvent vkDestroyEvent;
PFN_vkGetEventStatus vkGetEventStatus;
PFN_vkSetEvent vkSetEvent;
PFN_vkResetEvent vkResetEvent;
PFN_vkCreateQueryPool vkCreateQueryPool;
PFN_vkDestroyQueryPool vkDestroyQueryPool;
PFN_vkGetQueryPoolResults vkGetQueryPoolResults;
PFN_vkCreateBuffer vkCreateBuffer;
PFN_vkDestroyBuffer vkDestroyBuffer;
PFN_vkCreateBufferView vkCreateBufferView;
PFN_vkDestroyBufferView vkDestroyBufferView;
PFN_vkCreateImage vkCreateImage;
PFN_vkDestroyImage vkDestroyImage;
PFN_vkGetImageSubresourceLayout vkGetImageSubresourceLayout;
PFN_vkCreateImageView vkCreateImageView;
PFN_vkDestroyImageView vkDestroyImageView;
PFN_vkCreateShaderModule vkCreateShaderModule;
PFN_vkDestroyShaderModule vkDestroyShaderModule;
PFN_vkCreatePipelineCache vkCreatePipelineCache;
PFN_vkDestroyPipelineCache vkDestroyPipelineCache;
PFN_vkGetPipelineCacheData vkGetPipelineCacheData;
PFN_vkMergePipelineCaches vkMergePipelineCaches;
PFN_vkCreateGraphicsPipelines vkCreateGraphicsPipelines;
PFN_vkCreateComputePipelines vkCreateComputePipelines;
PFN_vkDestroyPipeline vkDestroyPipeline;
PFN_vkCreatePipelineLayout vkCreatePipelineLayout;
PFN_vkDestroyPipelineLayout vkDestroyPipelineLayout;
PFN_vkCreateSampler vkCreateSampler;
PFN_vkDestroySampler vkDestroySampler;
PFN_vkCreateDescriptorSetLayout vkCreateDescriptorSetLayout;
PFN_vkDestroyDescriptorSetLayout vkDestroyDescriptorSetLayout;
PFN_vkCreateDescriptorPool vkCreateDescriptorPool;
PFN_vkDestroyDescriptorPool vkDestroyDescriptorPool;
PFN_vkResetDescriptorPool vkResetDescriptorPool;
PFN_vkAllocateDescriptorSets vkAllocateDescriptorSets;
PFN_vkFreeDescriptorSets vkFreeDescriptorSets;
PFN_vkUpdateDescriptorSets vkUpdateDescriptorSets;
PFN_vkCreateFramebuffer vkCreateFramebuffer;
PFN_vkDestroyFramebuffer vkDestroyFramebuffer;
PFN_vkCreateRenderPass vkCreateRenderPass;
PFN_vkDestroyRenderPass vkDestroyRenderPass;
PFN_vkGetRenderAreaGranularity vkGetRenderAreaGranularity;
PFN_vkCreateCommandPool vkCreateCommandPool;
PFN_vkDestroyCommandPool vkDestroyCommandPool;
PFN_vkResetCommandPool vkResetCommandPool;
PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers;
PFN_vkFreeCommandBuffers vkFreeCommandBuffers;
PFN_vkBeginCommandBuffer vkBeginCommandBuffer;
PFN_vkEndCommandBuffer vkEndCommandBuffer;
PFN_vkResetCommandBuffer vkResetCommandBuffer;
PFN_vkCmdBindPipeline vkCmdBindPipeline;
PFN_vkCmdSetViewport vkCmdSetViewport;
PFN_vkCmdSetScissor vkCmdSetScissor;
PFN_vkCmdSetLineWidth vkCmdSetLineWidth;
PFN_vkCmdSetDepthBias vkCmdSetDepthBias;
PFN_vkCmdSetBlendConstants vkCmdSetBlendConstants;
PFN_vkCmdSetDepthBounds vkCmdSetDepthBounds;
PFN_vkCmdSetStencilCompareMask vkCmdSetStencilCompareMask;
PFN_vkCmdSetStencilWriteMask vkCmdSetStencilWriteMask;
PFN_vkCmdSetStencilReference vkCmdSetStencilReference;
PFN_vkCmdBindDescriptorSets vkCmdBindDescriptorSets;
PFN_vkCmdBindIndexBuffer vkCmdBindIndexBuffer;
PFN_vkCmdBindVertexBuffers vkCmdBindVertexBuffers;
PFN_vkCmdDraw vkCmdDraw;
PFN_vkCmdDrawIndexed vkCmdDrawIndexed;
PFN_vkCmdDrawIndirect vkCmdDrawIndirect;
PFN_vkCmdDrawIndexedIndirect vkCmdDrawIndexedIndirect;
PFN_vkCmdDispatch vkCmdDispatch;
PFN_vkCmdDispatchIndirect vkCmdDispatchIndirect;
PFN_vkCmdCopyBuffer vkCmdCopyBuffer;
PFN_vkCmdCopyImage vkCmdCopyImage;
PFN_vkCmdBlitImage vkCmdBlitImage;
PFN_vkCmdCopyBufferToImage vkCmdCopyBufferToImage;
PFN_vkCmdCopyImageToBuffer vkCmdCopyImageToBuffer;
PFN_vkCmdUpdateBuffer vkCmdUpdateBuffer;
PFN_vkCmdFillBuffer vkCmdFillBuffer;
PFN_vkCmdClearColorImage vkCmdClearColorImage;
PFN_vkCmdClearDepthStencilImage vkCmdClearDepthStencilImage;
PFN_vkCmdClearAttachments vkCmdClearAttachments;
PFN_vkCmdResolveImage vkCmdResolveImage;
PFN_vkCmdSetEvent vkCmdSetEvent;
PFN_vkCmdResetEvent vkCmdResetEvent;
PFN_vkCmdWaitEvents vkCmdWaitEvents;
PFN_vkCmdPipelineBarrier vkCmdPipelineBarrier;
PFN_vkCmdBeginQuery vkCmdBeginQuery;
PFN_vkCmdEndQuery vkCmdEndQuery;
PFN_vkCmdResetQueryPool vkCmdResetQueryPool;
PFN_vkCmdWriteTimestamp vkCmdWriteTimestamp;
PFN_vkCmdCopyQueryPoolResults vkCmdCopyQueryPoolResults;
PFN_vkCmdPushConstants vkCmdPushConstants;
PFN_vkCmdBeginRenderPass vkCmdBeginRenderPass;
PFN_vkCmdNextSubpass vkCmdNextSubpass;
PFN_vkCmdEndRenderPass vkCmdEndRenderPass;
PFN_vkCmdExecuteCommands vkCmdExecuteCommands;
PFN_vkEnumerateInstanceVersion vkEnumerateInstanceVersion;
PFN_vkBindBufferMemory2 vkBindBufferMemory2;
PFN_vkBindImageMemory2 vkBindImageMemory2;
PFN_vkGetDeviceGroupPeerMemoryFeatures vkGetDeviceGroupPeerMemoryFeatures;
PFN_vkCmdSetDeviceMask vkCmdSetDeviceMask;
PFN_vkCmdDispatchBase vkCmdDispatchBase;
PFN_vkEnumeratePhysicalDeviceGroups vkEnumeratePhysicalDeviceGroups;
PFN_vkGetImageMemoryRequirements2 vkGetImageMemoryRequirements2;
PFN_vkGetBufferMemoryRequirements2 vkGetBufferMemoryRequirements2;
PFN_vkGetImageSparseMemoryRequirements2 vkGetImageSparseMemoryRequirements2;
PFN_vkGetPhysicalDeviceFeatures2 vkGetPhysicalDeviceFeatures2;
PFN_vkGetPhysicalDeviceProperties2 vkGetPhysicalDeviceProperties2;
PFN_vkGetPhysicalDeviceFormatProperties2 vkGetPhysicalDeviceFormatProperties2;
PFN_vkGetPhysicalDeviceImageFormatProperties2 vkGetPhysicalDeviceImageFormatProperties2;
PFN_vkGetPhysicalDeviceQueueFamilyProperties2 vkGetPhysicalDeviceQueueFamilyProperties2;
PFN_vkGetPhysicalDeviceMemoryProperties2 vkGetPhysicalDeviceMemoryProperties2;
PFN_vkGetPhysicalDeviceSparseImageFormatProperties2 vkGetPhysicalDeviceSparseImageFormatProperties2;
PFN_vkTrimCommandPool vkTrimCommandPool;
PFN_vkGetDeviceQueue2 vkGetDeviceQueue2;
PFN_vkCreateSamplerYcbcrConversion vkCreateSamplerYcbcrConversion;
PFN_vkDestroySamplerYcbcrConversion vkDestroySamplerYcbcrConversion;
PFN_vkCreateDescriptorUpdateTemplate vkCreateDescriptorUpdateTemplate;
PFN_vkDestroyDescriptorUpdateTemplate vkDestroyDescriptorUpdateTemplate;
PFN_vkUpdateDescriptorSetWithTemplate vkUpdateDescriptorSetWithTemplate;
PFN_vkGetPhysicalDeviceExternalBufferProperties vkGetPhysicalDeviceExternalBufferProperties;
PFN_vkGetPhysicalDeviceExternalFenceProperties vkGetPhysicalDeviceExternalFenceProperties;
PFN_vkGetPhysicalDeviceExternalSemaphoreProperties vkGetPhysicalDeviceExternalSemaphoreProperties;
PFN_vkGetDescriptorSetLayoutSupport vkGetDescriptorSetLayoutSupport;
PFN_vkCmdDrawIndirectCount vkCmdDrawIndirectCount;
PFN_vkCmdDrawIndexedIndirectCount vkCmdDrawIndexedIndirectCount;
PFN_vkCreateRenderPass2 vkCreateRenderPass2;
PFN_vkCmdBeginRenderPass2 vkCmdBeginRenderPass2;
PFN_vkCmdNextSubpass2 vkCmdNextSubpass2;
PFN_vkCmdEndRenderPass2 vkCmdEndRenderPass2;
PFN_vkResetQueryPool vkResetQueryPool;
PFN_vkGetSemaphoreCounterValue vkGetSemaphoreCounterValue;
PFN_vkWaitSemaphores vkWaitSemaphores;
PFN_vkSignalSemaphore vkSignalSemaphore;
PFN_vkGetBufferDeviceAddress vkGetBufferDeviceAddress;
PFN_vkGetBufferOpaqueCaptureAddress vkGetBufferOpaqueCaptureAddress;
PFN_vkGetDeviceMemoryOpaqueCaptureAddress vkGetDeviceMemoryOpaqueCaptureAddress;
PFN_vkGetPhysicalDeviceToolProperties vkGetPhysicalDeviceToolProperties;
PFN_vkCreatePrivateDataSlot vkCreatePrivateDataSlot;
PFN_vkDestroyPrivateDataSlot vkDestroyPrivateDataSlot;
PFN_vkSetPrivateData vkSetPrivateData;
PFN_vkGetPrivateData vkGetPrivateData;
PFN_vkCmdSetEvent2 vkCmdSetEvent2;
PFN_vkCmdResetEvent2 vkCmdResetEvent2;
PFN_vkCmdWaitEvents2 vkCmdWaitEvents2;
PFN_vkCmdPipelineBarrier2 vkCmdPipelineBarrier2;
PFN_vkCmdWriteTimestamp2 vkCmdWriteTimestamp2;
PFN_vkQueueSubmit2 vkQueueSubmit2;
PFN_vkCmdCopyBuffer2 vkCmdCopyBuffer2;
PFN_vkCmdCopyImage2 vkCmdCopyImage2;
PFN_vkCmdCopyBufferToImage2 vkCmdCopyBufferToImage2;
PFN_vkCmdCopyImageToBuffer2 vkCmdCopyImageToBuffer2;
PFN_vkCmdBlitImage2 vkCmdBlitImage2;
PFN_vkCmdResolveImage2 vkCmdResolveImage2;
PFN_vkCmdBeginRendering vkCmdBeginRendering;
PFN_vkCmdEndRendering vkCmdEndRendering;
PFN_vkCmdSetCullMode vkCmdSetCullMode;
PFN_vkCmdSetFrontFace vkCmdSetFrontFace;
PFN_vkCmdSetPrimitiveTopology vkCmdSetPrimitiveTopology;
PFN_vkCmdSetViewportWithCount vkCmdSetViewportWithCount;
PFN_vkCmdSetScissorWithCount vkCmdSetScissorWithCount;
PFN_vkCmdBindVertexBuffers2 vkCmdBindVertexBuffers2;
PFN_vkCmdSetDepthTestEnable vkCmdSetDepthTestEnable;
PFN_vkCmdSetDepthWriteEnable vkCmdSetDepthWriteEnable;
PFN_vkCmdSetDepthCompareOp vkCmdSetDepthCompareOp;
PFN_vkCmdSetDepthBoundsTestEnable vkCmdSetDepthBoundsTestEnable;
PFN_vkCmdSetStencilTestEnable vkCmdSetStencilTestEnable;
PFN_vkCmdSetStencilOp vkCmdSetStencilOp;
PFN_vkCmdSetRasterizerDiscardEnable vkCmdSetRasterizerDiscardEnable;
PFN_vkCmdSetDepthBiasEnable vkCmdSetDepthBiasEnable;
PFN_vkCmdSetPrimitiveRestartEnable vkCmdSetPrimitiveRestartEnable;
PFN_vkGetDeviceBufferMemoryRequirements vkGetDeviceBufferMemoryRequirements;
PFN_vkGetDeviceImageMemoryRequirements vkGetDeviceImageMemoryRequirements;
PFN_vkGetDeviceImageSparseMemoryRequirements vkGetDeviceImageSparseMemoryRequirements;
PFN_vkCmdSetLineStipple vkCmdSetLineStipple;
PFN_vkMapMemory2 vkMapMemory2;
PFN_vkUnmapMemory2 vkUnmapMemory2;
PFN_vkCmdBindIndexBuffer2 vkCmdBindIndexBuffer2;
PFN_vkGetRenderingAreaGranularity vkGetRenderingAreaGranularity;
PFN_vkGetDeviceImageSubresourceLayout vkGetDeviceImageSubresourceLayout;
PFN_vkGetImageSubresourceLayout2 vkGetImageSubresourceLayout2;
PFN_vkCmdPushDescriptorSet vkCmdPushDescriptorSet;
PFN_vkCmdPushDescriptorSetWithTemplate vkCmdPushDescriptorSetWithTemplate;
PFN_vkCmdSetRenderingAttachmentLocations vkCmdSetRenderingAttachmentLocations;
PFN_vkCmdSetRenderingInputAttachmentIndices vkCmdSetRenderingInputAttachmentIndices;
PFN_vkCmdBindDescriptorSets2 vkCmdBindDescriptorSets2;
PFN_vkCmdPushConstants2 vkCmdPushConstants2;
PFN_vkCmdPushDescriptorSet2 vkCmdPushDescriptorSet2;
PFN_vkCmdPushDescriptorSetWithTemplate2 vkCmdPushDescriptorSetWithTemplate2;
PFN_vkCopyMemoryToImage vkCopyMemoryToImage;
PFN_vkCopyImageToMemory vkCopyImageToMemory;
PFN_vkCopyImageToImage vkCopyImageToImage;
PFN_vkTransitionImageLayout vkTransitionImageLayout;
PFN_vkDestroySurfaceKHR vkDestroySurfaceKHR;
PFN_vkGetPhysicalDeviceSurfaceSupportKHR vkGetPhysicalDeviceSurfaceSupportKHR;
PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
PFN_vkGetPhysicalDeviceSurfaceFormatsKHR vkGetPhysicalDeviceSurfaceFormatsKHR;
PFN_vkGetPhysicalDeviceSurfacePresentModesKHR vkGetPhysicalDeviceSurfacePresentModesKHR;
PFN_vkCreateSwapchainKHR vkCreateSwapchainKHR;
PFN_vkDestroySwapchainKHR vkDestroySwapchainKHR;
PFN_vkGetSwapchainImagesKHR vkGetSwapchainImagesKHR;
PFN_vkAcquireNextImageKHR vkAcquireNextImageKHR;
PFN_vkQueuePresentKHR vkQueuePresentKHR;
PFN_vkGetDeviceGroupPresentCapabilitiesKHR vkGetDeviceGroupPresentCapabilitiesKHR;
PFN_vkGetDeviceGroupSurfacePresentModesKHR vkGetDeviceGroupSurfacePresentModesKHR;
PFN_vkGetPhysicalDevicePresentRectanglesKHR vkGetPhysicalDevicePresentRectanglesKHR;
PFN_vkAcquireNextImage2KHR vkAcquireNextImage2KHR;
PFN_vkGetPhysicalDeviceDisplayPropertiesKHR vkGetPhysicalDeviceDisplayPropertiesKHR;
PFN_vkGetPhysicalDeviceDisplayPlanePropertiesKHR vkGetPhysicalDeviceDisplayPlanePropertiesKHR;
PFN_vkGetDisplayPlaneSupportedDisplaysKHR vkGetDisplayPlaneSupportedDisplaysKHR;
PFN_vkGetDisplayModePropertiesKHR vkGetDisplayModePropertiesKHR;
PFN_vkCreateDisplayModeKHR vkCreateDisplayModeKHR;
PFN_vkGetDisplayPlaneCapabilitiesKHR vkGetDisplayPlaneCapabilitiesKHR;
PFN_vkCreateDisplayPlaneSurfaceKHR vkCreateDisplayPlaneSurfaceKHR;
PFN_vkCreateSharedSwapchainsKHR vkCreateSharedSwapchainsKHR;
PFN_vkGetPhysicalDeviceVideoCapabilitiesKHR vkGetPhysicalDeviceVideoCapabilitiesKHR;
PFN_vkGetPhysicalDeviceVideoFormatPropertiesKHR vkGetPhysicalDeviceVideoFormatPropertiesKHR;
PFN_vkCreateVideoSessionKHR vkCreateVideoSessionKHR;
PFN_vkDestroyVideoSessionKHR vkDestroyVideoSessionKHR;
PFN_vkGetVideoSessionMemoryRequirementsKHR vkGetVideoSessionMemoryRequirementsKHR;
PFN_vkBindVideoSessionMemoryKHR vkBindVideoSessionMemoryKHR;
PFN_vkCreateVideoSessionParametersKHR vkCreateVideoSessionParametersKHR;
PFN_vkUpdateVideoSessionParametersKHR vkUpdateVideoSessionParametersKHR;
PFN_vkDestroyVideoSessionParametersKHR vkDestroyVideoSessionParametersKHR;
PFN_vkCmdBeginVideoCodingKHR vkCmdBeginVideoCodingKHR;
PFN_vkCmdEndVideoCodingKHR vkCmdEndVideoCodingKHR;
PFN_vkCmdControlVideoCodingKHR vkCmdControlVideoCodingKHR;
PFN_vkCmdDecodeVideoKHR vkCmdDecodeVideoKHR;
PFN_vkCmdBeginRenderingKHR vkCmdBeginRenderingKHR;
PFN_vkCmdEndRenderingKHR vkCmdEndRenderingKHR;
PFN_vkGetPhysicalDeviceFeatures2KHR vkGetPhysicalDeviceFeatures2KHR;
PFN_vkGetPhysicalDeviceProperties2KHR vkGetPhysicalDeviceProperties2KHR;
PFN_vkGetPhysicalDeviceFormatProperties2KHR vkGetPhysicalDeviceFormatProperties2KHR;
PFN_vkGetPhysicalDeviceImageFormatProperties2KHR vkGetPhysicalDeviceImageFormatProperties2KHR;
PFN_vkGetPhysicalDeviceQueueFamilyProperties2KHR vkGetPhysicalDeviceQueueFamilyProperties2KHR;
PFN_vkGetPhysicalDeviceMemoryProperties2KHR vkGetPhysicalDeviceMemoryProperties2KHR;
PFN_vkGetPhysicalDeviceSparseImageFormatProperties2KHR vkGetPhysicalDeviceSparseImageFormatProperties2KHR;
PFN_vkGetDeviceGroupPeerMemoryFeaturesKHR vkGetDeviceGroupPeerMemoryFeaturesKHR;
PFN_vkCmdSetDeviceMaskKHR vkCmdSetDeviceMaskKHR;
PFN_vkCmdDispatchBaseKHR vkCmdDispatchBaseKHR;
PFN_vkTrimCommandPoolKHR vkTrimCommandPoolKHR;
PFN_vkEnumeratePhysicalDeviceGroupsKHR vkEnumeratePhysicalDeviceGroupsKHR;
PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR vkGetPhysicalDeviceExternalBufferPropertiesKHR;
PFN_vkGetMemoryFdKHR vkGetMemoryFdKHR;
PFN_vkGetMemoryFdPropertiesKHR vkGetMemoryFdPropertiesKHR;
PFN_vkGetPhysicalDeviceExternalSemaphorePropertiesKHR vkGetPhysicalDeviceExternalSemaphorePropertiesKHR;
PFN_vkImportSemaphoreFdKHR vkImportSemaphoreFdKHR;
PFN_vkGetSemaphoreFdKHR vkGetSemaphoreFdKHR;
PFN_vkCmdPushDescriptorSetKHR vkCmdPushDescriptorSetKHR;
PFN_vkCmdPushDescriptorSetWithTemplateKHR vkCmdPushDescriptorSetWithTemplateKHR;
PFN_vkCreateDescriptorUpdateTemplateKHR vkCreateDescriptorUpdateTemplateKHR;
PFN_vkDestroyDescriptorUpdateTemplateKHR vkDestroyDescriptorUpdateTemplateKHR;
PFN_vkUpdateDescriptorSetWithTemplateKHR vkUpdateDescriptorSetWithTemplateKHR;
PFN_vkCreateRenderPass2KHR vkCreateRenderPass2KHR;
PFN_vkCmdBeginRenderPass2KHR vkCmdBeginRenderPass2KHR;
PFN_vkCmdNextSubpass2KHR vkCmdNextSubpass2KHR;
PFN_vkCmdEndRenderPass2KHR vkCmdEndRenderPass2KHR;
PFN_vkGetSwapchainStatusKHR vkGetSwapchainStatusKHR;
PFN_vkGetPhysicalDeviceExternalFencePropertiesKHR vkGetPhysicalDeviceExternalFencePropertiesKHR;
PFN_vkImportFenceFdKHR vkImportFenceFdKHR;
PFN_vkGetFenceFdKHR vkGetFenceFdKHR;
PFN_vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR;
PFN_vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR;
PFN_vkAcquireProfilingLockKHR vkAcquireProfilingLockKHR;
PFN_vkReleaseProfilingLockKHR vkReleaseProfilingLockKHR;
PFN_vkGetPhysicalDeviceSurfaceCapabilities2KHR vkGetPhysicalDeviceSurfaceCapabilities2KHR;
PFN_vkGetPhysicalDeviceSurfaceFormats2KHR vkGetPhysicalDeviceSurfaceFormats2KHR;
PFN_vkGetPhysicalDeviceDisplayProperties2KHR vkGetPhysicalDeviceDisplayProperties2KHR;
PFN_vkGetPhysicalDeviceDisplayPlaneProperties2KHR vkGetPhysicalDeviceDisplayPlaneProperties2KHR;
PFN_vkGetDisplayModeProperties2KHR vkGetDisplayModeProperties2KHR;
PFN_vkGetDisplayPlaneCapabilities2KHR vkGetDisplayPlaneCapabilities2KHR;
PFN_vkGetImageMemoryRequirements2KHR vkGetImageMemoryRequirements2KHR;
PFN_vkGetBufferMemoryRequirements2KHR vkGetBufferMemoryRequirements2KHR;
PFN_vkGetImageSparseMemoryRequirements2KHR vkGetImageSparseMemoryRequirements2KHR;
PFN_vkCreateSamplerYcbcrConversionKHR vkCreateSamplerYcbcrConversionKHR;
PFN_vkDestroySamplerYcbcrConversionKHR vkDestroySamplerYcbcrConversionKHR;
PFN_vkBindBufferMemory2KHR vkBindBufferMemory2KHR;
PFN_vkBindImageMemory2KHR vkBindImageMemory2KHR;
PFN_vkGetDescriptorSetLayoutSupportKHR vkGetDescriptorSetLayoutSupportKHR;
PFN_vkCmdDrawIndirectCountKHR vkCmdDrawIndirectCountKHR;
PFN_vkCmdDrawIndexedIndirectCountKHR vkCmdDrawIndexedIndirectCountKHR;
PFN_vkGetSemaphoreCounterValueKHR vkGetSemaphoreCounterValueKHR;
PFN_vkWaitSemaphoresKHR vkWaitSemaphoresKHR;
PFN_vkSignalSemaphoreKHR vkSignalSemaphoreKHR;
PFN_vkGetPhysicalDeviceFragmentShadingRatesKHR vkGetPhysicalDeviceFragmentShadingRatesKHR;
PFN_vkCmdSetFragmentShadingRateKHR vkCmdSetFragmentShadingRateKHR;
PFN_vkCmdSetRenderingAttachmentLocationsKHR vkCmdSetRenderingAttachmentLocationsKHR;
PFN_vkCmdSetRenderingInputAttachmentIndicesKHR vkCmdSetRenderingInputAttachmentIndicesKHR;
PFN_vkWaitForPresentKHR vkWaitForPresentKHR;
PFN_vkGetBufferDeviceAddressKHR vkGetBufferDeviceAddressKHR;
PFN_vkGetBufferOpaqueCaptureAddressKHR vkGetBufferOpaqueCaptureAddressKHR;
PFN_vkGetDeviceMemoryOpaqueCaptureAddressKHR vkGetDeviceMemoryOpaqueCaptureAddressKHR;
PFN_vkCreateDeferredOperationKHR vkCreateDeferredOperationKHR;
PFN_vkDestroyDeferredOperationKHR vkDestroyDeferredOperationKHR;
PFN_vkGetDeferredOperationMaxConcurrencyKHR vkGetDeferredOperationMaxConcurrencyKHR;
PFN_vkGetDeferredOperationResultKHR vkGetDeferredOperationResultKHR;
PFN_vkDeferredOperationJoinKHR vkDeferredOperationJoinKHR;
PFN_vkGetPipelineExecutablePropertiesKHR vkGetPipelineExecutablePropertiesKHR;
PFN_vkGetPipelineExecutableStatisticsKHR vkGetPipelineExecutableStatisticsKHR;
PFN_vkGetPipelineExecutableInternalRepresentationsKHR vkGetPipelineExecutableInternalRepresentationsKHR;
PFN_vkMapMemory2KHR vkMapMemory2KHR;
PFN_vkUnmapMemory2KHR vkUnmapMemory2KHR;
PFN_vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR;
PFN_vkGetEncodedVideoSessionParametersKHR vkGetEncodedVideoSessionParametersKHR;
PFN_vkCmdEncodeVideoKHR vkCmdEncodeVideoKHR;
PFN_vkCmdSetEvent2KHR vkCmdSetEvent2KHR;
PFN_vkCmdResetEvent2KHR vkCmdResetEvent2KHR;
PFN_vkCmdWaitEvents2KHR vkCmdWaitEvents2KHR;
PFN_vkCmdPipelineBarrier2KHR vkCmdPipelineBarrier2KHR;
PFN_vkCmdWriteTimestamp2KHR vkCmdWriteTimestamp2KHR;
PFN_vkQueueSubmit2KHR vkQueueSubmit2KHR;
PFN_vkCmdCopyBuffer2KHR vkCmdCopyBuffer2KHR;
PFN_vkCmdCopyImage2KHR vkCmdCopyImage2KHR;
PFN_vkCmdCopyBufferToImage2KHR vkCmdCopyBufferToImage2KHR;
PFN_vkCmdCopyImageToBuffer2KHR vkCmdCopyImageToBuffer2KHR;
PFN_vkCmdBlitImage2KHR vkCmdBlitImage2KHR;
PFN_vkCmdResolveImage2KHR vkCmdResolveImage2KHR;
PFN_vkCmdTraceRaysIndirect2KHR vkCmdTraceRaysIndirect2KHR;
PFN_vkGetDeviceBufferMemoryRequirementsKHR vkGetDeviceBufferMemoryRequirementsKHR;
PFN_vkGetDeviceImageMemoryRequirementsKHR vkGetDeviceImageMemoryRequirementsKHR;
PFN_vkGetDeviceImageSparseMemoryRequirementsKHR vkGetDeviceImageSparseMemoryRequirementsKHR;
PFN_vkCmdBindIndexBuffer2KHR vkCmdBindIndexBuffer2KHR;
PFN_vkGetRenderingAreaGranularityKHR vkGetRenderingAreaGranularityKHR;
PFN_vkGetDeviceImageSubresourceLayoutKHR vkGetDeviceImageSubresourceLayoutKHR;
PFN_vkGetImageSubresourceLayout2KHR vkGetImageSubresourceLayout2KHR;
PFN_vkCreatePipelineBinariesKHR vkCreatePipelineBinariesKHR;
PFN_vkDestroyPipelineBinaryKHR vkDestroyPipelineBinaryKHR;
PFN_vkGetPipelineKeyKHR vkGetPipelineKeyKHR;
PFN_vkGetPipelineBinaryDataKHR vkGetPipelineBinaryDataKHR;
PFN_vkReleaseCapturedPipelineDataKHR vkReleaseCapturedPipelineDataKHR;
PFN_vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR;
PFN_vkCmdSetLineStippleKHR vkCmdSetLineStippleKHR;
PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsKHR vkGetPhysicalDeviceCalibrateableTimeDomainsKHR;
PFN_vkGetCalibratedTimestampsKHR vkGetCalibratedTimestampsKHR;
PFN_vkCmdBindDescriptorSets2KHR vkCmdBindDescriptorSets2KHR;
PFN_vkCmdPushConstants2KHR vkCmdPushConstants2KHR;
PFN_vkCmdPushDescriptorSet2KHR vkCmdPushDescriptorSet2KHR;
PFN_vkCmdPushDescriptorSetWithTemplate2KHR vkCmdPushDescriptorSetWithTemplate2KHR;
PFN_vkCmdSetDescriptorBufferOffsets2EXT vkCmdSetDescriptorBufferOffsets2EXT;
PFN_vkCmdBindDescriptorBufferEmbeddedSamplers2EXT vkCmdBindDescriptorBufferEmbeddedSamplers2EXT;
PFN_vkCreateAccelerationStructureKHR vkCreateAccelerationStructureKHR;
PFN_vkDestroyAccelerationStructureKHR vkDestroyAccelerationStructureKHR;
PFN_vkCmdBuildAccelerationStructuresKHR vkCmdBuildAccelerationStructuresKHR;
PFN_vkCmdBuildAccelerationStructuresIndirectKHR vkCmdBuildAccelerationStructuresIndirectKHR;
PFN_vkBuildAccelerationStructuresKHR vkBuildAccelerationStructuresKHR;
PFN_vkCopyAccelerationStructureKHR vkCopyAccelerationStructureKHR;
PFN_vkCopyAccelerationStructureToMemoryKHR vkCopyAccelerationStructureToMemoryKHR;
PFN_vkCopyMemoryToAccelerationStructureKHR vkCopyMemoryToAccelerationStructureKHR;
PFN_vkWriteAccelerationStructuresPropertiesKHR vkWriteAccelerationStructuresPropertiesKHR;
PFN_vkCmdCopyAccelerationStructureKHR vkCmdCopyAccelerationStructureKHR;
PFN_vkCmdCopyAccelerationStructureToMemoryKHR vkCmdCopyAccelerationStructureToMemoryKHR;
PFN_vkCmdCopyMemoryToAccelerationStructureKHR vkCmdCopyMemoryToAccelerationStructureKHR;
PFN_vkGetAccelerationStructureDeviceAddressKHR vkGetAccelerationStructureDeviceAddressKHR;
PFN_vkCmdWriteAccelerationStructuresPropertiesKHR vkCmdWriteAccelerationStructuresPropertiesKHR;
PFN_vkGetDeviceAccelerationStructureCompatibilityKHR vkGetDeviceAccelerationStructureCompatibilityKHR;
PFN_vkGetAccelerationStructureBuildSizesKHR vkGetAccelerationStructureBuildSizesKHR;
PFN_vkCmdTraceRaysKHR vkCmdTraceRaysKHR;
PFN_vkCreateRayTracingPipelinesKHR vkCreateRayTracingPipelinesKHR;
PFN_vkGetRayTracingCaptureReplayShaderGroupHandlesKHR vkGetRayTracingCaptureReplayShaderGroupHandlesKHR;
PFN_vkCmdTraceRaysIndirectKHR vkCmdTraceRaysIndirectKHR;
PFN_vkGetRayTracingShaderGroupStackSizeKHR vkGetRayTracingShaderGroupStackSizeKHR;
PFN_vkCmdSetRayTracingPipelineStackSizeKHR vkCmdSetRayTracingPipelineStackSizeKHR;

#ifdef VK_USE_PLATFORM_ANDROID_KHR
PFN_vkCreateAndroidSurfaceKHR vkCreateAndroidSurfaceKHR;
#endif

#ifdef VK_USE_PLATFORM_WAYLAND_KHR
PFN_vkCreateWaylandSurfaceKHR vkCreateWaylandSurfaceKHR;
PFN_vkGetPhysicalDeviceWaylandPresentationSupportKHR vkGetPhysicalDeviceWaylandPresentationSupportKHR;
#endif

#ifdef VK_USE_PLATFORM_WIN32_KHR
PFN_vkCreateWin32SurfaceKHR vkCreateWin32SurfaceKHR;
PFN_vkGetPhysicalDeviceWin32PresentationSupportKHR vkGetPhysicalDeviceWin32PresentationSupportKHR;
PFN_vkGetMemoryWin32HandleKHR vkGetMemoryWin32HandleKHR;
PFN_vkGetMemoryWin32HandlePropertiesKHR vkGetMemoryWin32HandlePropertiesKHR;
PFN_vkImportSemaphoreWin32HandleKHR vkImportSemaphoreWin32HandleKHR;
PFN_vkGetSemaphoreWin32HandleKHR vkGetSemaphoreWin32HandleKHR;
PFN_vkImportFenceWin32HandleKHR vkImportFenceWin32HandleKHR;
PFN_vkGetFenceWin32HandleKHR vkGetFenceWin32HandleKHR;
#endif

#ifdef VK_USE_PLATFORM_XCB_KHR
PFN_vkCreateXcbSurfaceKHR vkCreateXcbSurfaceKHR;
PFN_vkGetPhysicalDeviceXcbPresentationSupportKHR vkGetPhysicalDeviceXcbPresentationSupportKHR;
#endif

#ifdef VK_USE_PLATFORM_XLIB_KHR
PFN_vkCreateXlibSurfaceKHR vkCreateXlibSurfaceKHR;
PFN_vkGetPhysicalDeviceXlibPresentationSupportKHR vkGetPhysicalDeviceXlibPresentationSupportKHR;
#endif

void vexLoadDeviceTable(VkDevice device, vexDeviceTable* table) {
# define LOAD_DEVICE_TABLE(PROC) table->PROC = (PFN_##PROC) vkGetDeviceProcAddr(device, #PROC);
    LOAD_DEVICE_TABLE(vkGetDeviceProcAddr)
    LOAD_DEVICE_TABLE(vkDestroyDevice)
    LOAD_DEVICE_TABLE(vkGetDeviceQueue)
    LOAD_DEVICE_TABLE(vkQueueSubmit)
    LOAD_DEVICE_TABLE(vkQueueWaitIdle)
    LOAD_DEVICE_TABLE(vkDeviceWaitIdle)
    LOAD_DEVICE_TABLE(vkAllocateMemory)
    LOAD_DEVICE_TABLE(vkFreeMemory)
    LOAD_DEVICE_TABLE(vkMapMemory)
    LOAD_DEVICE_TABLE(vkUnmapMemory)
    LOAD_DEVICE_TABLE(vkFlushMappedMemoryRanges)
    LOAD_DEVICE_TABLE(vkInvalidateMappedMemoryRanges)
    LOAD_DEVICE_TABLE(vkGetDeviceMemoryCommitment)
    LOAD_DEVICE_TABLE(vkBindBufferMemory)
    LOAD_DEVICE_TABLE(vkBindImageMemory)
    LOAD_DEVICE_TABLE(vkGetBufferMemoryRequirements)
    LOAD_DEVICE_TABLE(vkGetImageMemoryRequirements)
    LOAD_DEVICE_TABLE(vkGetImageSparseMemoryRequirements)
    LOAD_DEVICE_TABLE(vkQueueBindSparse)
    LOAD_DEVICE_TABLE(vkCreateFence)
    LOAD_DEVICE_TABLE(vkDestroyFence)
    LOAD_DEVICE_TABLE(vkResetFences)
    LOAD_DEVICE_TABLE(vkGetFenceStatus)
    LOAD_DEVICE_TABLE(vkWaitForFences)
    LOAD_DEVICE_TABLE(vkCreateSemaphore)
    LOAD_DEVICE_TABLE(vkDestroySemaphore)
    LOAD_DEVICE_TABLE(vkCreateEvent)
    LOAD_DEVICE_TABLE(vkDestroyEvent)
    LOAD_DEVICE_TABLE(vkGetEventStatus)
    LOAD_DEVICE_TABLE(vkSetEvent)
    LOAD_DEVICE_TABLE(vkResetEvent)
    LOAD_DEVICE_TABLE(vkCreateQueryPool)
    LOAD_DEVICE_TABLE(vkDestroyQueryPool)
    LOAD_DEVICE_TABLE(vkGetQueryPoolResults)
    LOAD_DEVICE_TABLE(vkCreateBuffer)
    LOAD_DEVICE_TABLE(vkDestroyBuffer)
    LOAD_DEVICE_TABLE(vkCreateBufferView)
    LOAD_DEVICE_TABLE(vkDestroyBufferView)
    LOAD_DEVICE_TABLE(vkCreateImage)
    LOAD_DEVICE_TABLE(vkDestroyImage)
    LOAD_DEVICE_TABLE(vkGetImageSubresourceLayout)
    LOAD_DEVICE_TABLE(vkCreateImageView)
    LOAD_DEVICE_TABLE(vkDestroyImageView)
    LOAD_DEVICE_TABLE(vkCreateShaderModule)
    LOAD_DEVICE_TABLE(vkDestroyShaderModule)
    LOAD_DEVICE_TABLE(vkCreatePipelineCache)
    LOAD_DEVICE_TABLE(vkDestroyPipelineCache)
    LOAD_DEVICE_TABLE(vkGetPipelineCacheData)
    LOAD_DEVICE_TABLE(vkMergePipelineCaches)
    LOAD_DEVICE_TABLE(vkCreateGraphicsPipelines)
    LOAD_DEVICE_TABLE(vkCreateComputePipelines)
    LOAD_DEVICE_TABLE(vkDestroyPipeline)
    LOAD_DEVICE_TABLE(vkCreatePipelineLayout)
    LOAD_DEVICE_TABLE(vkDestroyPipelineLayout)
    LOAD_DEVICE_TABLE(vkCreateSampler)
    LOAD_DEVICE_TABLE(vkDestroySampler)
    LOAD_DEVICE_TABLE(vkCreateDescriptorSetLayout)
    LOAD_DEVICE_TABLE(vkDestroyDescriptorSetLayout)
    LOAD_DEVICE_TABLE(vkCreateDescriptorPool)
    LOAD_DEVICE_TABLE(vkDestroyDescriptorPool)
    LOAD_DEVICE_TABLE(vkResetDescriptorPool)
    LOAD_DEVICE_TABLE(vkAllocateDescriptorSets)
    LOAD_DEVICE_TABLE(vkFreeDescriptorSets)
    LOAD_DEVICE_TABLE(vkUpdateDescriptorSets)
    LOAD_DEVICE_TABLE(vkCreateFramebuffer)
    LOAD_DEVICE_TABLE(vkDestroyFramebuffer)
    LOAD_DEVICE_TABLE(vkCreateRenderPass)
    LOAD_DEVICE_TABLE(vkDestroyRenderPass)
    LOAD_DEVICE_TABLE(vkGetRenderAreaGranularity)
    LOAD_DEVICE_TABLE(vkCreateCommandPool)
    LOAD_DEVICE_TABLE(vkDestroyCommandPool)
    LOAD_DEVICE_TABLE(vkResetCommandPool)
    LOAD_DEVICE_TABLE(vkAllocateCommandBuffers)
    LOAD_DEVICE_TABLE(vkFreeCommandBuffers)
    LOAD_DEVICE_TABLE(vkBeginCommandBuffer)
    LOAD_DEVICE_TABLE(vkEndCommandBuffer)
    LOAD_DEVICE_TABLE(vkResetCommandBuffer)
    LOAD_DEVICE_TABLE(vkCmdBindPipeline)
    LOAD_DEVICE_TABLE(vkCmdSetViewport)
    LOAD_DEVICE_TABLE(vkCmdSetScissor)
    LOAD_DEVICE_TABLE(vkCmdSetLineWidth)
    LOAD_DEVICE_TABLE(vkCmdSetDepthBias)
    LOAD_DEVICE_TABLE(vkCmdSetBlendConstants)
    LOAD_DEVICE_TABLE(vkCmdSetDepthBounds)
    LOAD_DEVICE_TABLE(vkCmdSetStencilCompareMask)
    LOAD_DEVICE_TABLE(vkCmdSetStencilWriteMask)
    LOAD_DEVICE_TABLE(vkCmdSetStencilReference)
    LOAD_DEVICE_TABLE(vkCmdBindDescriptorSets)
    LOAD_DEVICE_TABLE(vkCmdBindIndexBuffer)
    LOAD_DEVICE_TABLE(vkCmdBindVertexBuffers)
    LOAD_DEVICE_TABLE(vkCmdDraw)
    LOAD_DEVICE_TABLE(vkCmdDrawIndexed)
    LOAD_DEVICE_TABLE(vkCmdDrawIndirect)
    LOAD_DEVICE_TABLE(vkCmdDrawIndexedIndirect)
    LOAD_DEVICE_TABLE(vkCmdDispatch)
    LOAD_DEVICE_TABLE(vkCmdDispatchIndirect)
    LOAD_DEVICE_TABLE(vkCmdCopyBuffer)
    LOAD_DEVICE_TABLE(vkCmdCopyImage)
    LOAD_DEVICE_TABLE(vkCmdBlitImage)
    LOAD_DEVICE_TABLE(vkCmdCopyBufferToImage)
    LOAD_DEVICE_TABLE(vkCmdCopyImageToBuffer)
    LOAD_DEVICE_TABLE(vkCmdUpdateBuffer)
    LOAD_DEVICE_TABLE(vkCmdFillBuffer)
    LOAD_DEVICE_TABLE(vkCmdClearColorImage)
    LOAD_DEVICE_TABLE(vkCmdClearDepthStencilImage)
    LOAD_DEVICE_TABLE(vkCmdClearAttachments)
    LOAD_DEVICE_TABLE(vkCmdResolveImage)
    LOAD_DEVICE_TABLE(vkCmdSetEvent)
    LOAD_DEVICE_TABLE(vkCmdResetEvent)
    LOAD_DEVICE_TABLE(vkCmdWaitEvents)
    LOAD_DEVICE_TABLE(vkCmdPipelineBarrier)
    LOAD_DEVICE_TABLE(vkCmdBeginQuery)
    LOAD_DEVICE_TABLE(vkCmdEndQuery)
    LOAD_DEVICE_TABLE(vkCmdResetQueryPool)
    LOAD_DEVICE_TABLE(vkCmdWriteTimestamp)
    LOAD_DEVICE_TABLE(vkCmdCopyQueryPoolResults)
    LOAD_DEVICE_TABLE(vkCmdPushConstants)
    LOAD_DEVICE_TABLE(vkCmdBeginRenderPass)
    LOAD_DEVICE_TABLE(vkCmdNextSubpass)
    LOAD_DEVICE_TABLE(vkCmdEndRenderPass)
    LOAD_DEVICE_TABLE(vkCmdExecuteCommands)
    LOAD_DEVICE_TABLE(vkBindBufferMemory2)
    LOAD_DEVICE_TABLE(vkBindImageMemory2)
    LOAD_DEVICE_TABLE(vkGetDeviceGroupPeerMemoryFeatures)
    LOAD_DEVICE_TABLE(vkCmdSetDeviceMask)
    LOAD_DEVICE_TABLE(vkCmdDispatchBase)
    LOAD_DEVICE_TABLE(vkGetImageMemoryRequirements2)
    LOAD_DEVICE_TABLE(vkGetBufferMemoryRequirements2)
    LOAD_DEVICE_TABLE(vkGetImageSparseMemoryRequirements2)
    LOAD_DEVICE_TABLE(vkTrimCommandPool)
    LOAD_DEVICE_TABLE(vkGetDeviceQueue2)
    LOAD_DEVICE_TABLE(vkCreateSamplerYcbcrConversion)
    LOAD_DEVICE_TABLE(vkDestroySamplerYcbcrConversion)
    LOAD_DEVICE_TABLE(vkCreateDescriptorUpdateTemplate)
    LOAD_DEVICE_TABLE(vkDestroyDescriptorUpdateTemplate)
    LOAD_DEVICE_TABLE(vkUpdateDescriptorSetWithTemplate)
    LOAD_DEVICE_TABLE(vkGetDescriptorSetLayoutSupport)
    LOAD_DEVICE_TABLE(vkCmdDrawIndirectCount)
    LOAD_DEVICE_TABLE(vkCmdDrawIndexedIndirectCount)
    LOAD_DEVICE_TABLE(vkCreateRenderPass2)
    LOAD_DEVICE_TABLE(vkCmdBeginRenderPass2)
    LOAD_DEVICE_TABLE(vkCmdNextSubpass2)
    LOAD_DEVICE_TABLE(vkCmdEndRenderPass2)
    LOAD_DEVICE_TABLE(vkResetQueryPool)
    LOAD_DEVICE_TABLE(vkGetSemaphoreCounterValue)
    LOAD_DEVICE_TABLE(vkWaitSemaphores)
    LOAD_DEVICE_TABLE(vkSignalSemaphore)
    LOAD_DEVICE_TABLE(vkGetBufferDeviceAddress)
    LOAD_DEVICE_TABLE(vkGetBufferOpaqueCaptureAddress)
    LOAD_DEVICE_TABLE(vkGetDeviceMemoryOpaqueCaptureAddress)
    LOAD_DEVICE_TABLE(vkCreatePrivateDataSlot)
    LOAD_DEVICE_TABLE(vkDestroyPrivateDataSlot)
    LOAD_DEVICE_TABLE(vkSetPrivateData)
    LOAD_DEVICE_TABLE(vkGetPrivateData)
    LOAD_DEVICE_TABLE(vkCmdSetEvent2)
    LOAD_DEVICE_TABLE(vkCmdResetEvent2)
    LOAD_DEVICE_TABLE(vkCmdWaitEvents2)
    LOAD_DEVICE_TABLE(vkCmdPipelineBarrier2)
    LOAD_DEVICE_TABLE(vkCmdWriteTimestamp2)
    LOAD_DEVICE_TABLE(vkQueueSubmit2)
    LOAD_DEVICE_TABLE(vkCmdCopyBuffer2)
    LOAD_DEVICE_TABLE(vkCmdCopyImage2)
    LOAD_DEVICE_TABLE(vkCmdCopyBufferToImage2)
    LOAD_DEVICE_TABLE(vkCmdCopyImageToBuffer2)
    LOAD_DEVICE_TABLE(vkCmdBlitImage2)
    LOAD_DEVICE_TABLE(vkCmdResolveImage2)
    LOAD_DEVICE_TABLE(vkCmdBeginRendering)
    LOAD_DEVICE_TABLE(vkCmdEndRendering)
    LOAD_DEVICE_TABLE(vkCmdSetCullMode)
    LOAD_DEVICE_TABLE(vkCmdSetFrontFace)
    LOAD_DEVICE_TABLE(vkCmdSetPrimitiveTopology)
    LOAD_DEVICE_TABLE(vkCmdSetViewportWithCount)
    LOAD_DEVICE_TABLE(vkCmdSetScissorWithCount)
    LOAD_DEVICE_TABLE(vkCmdBindVertexBuffers2)
    LOAD_DEVICE_TABLE(vkCmdSetDepthTestEnable)
    LOAD_DEVICE_TABLE(vkCmdSetDepthWriteEnable)
    LOAD_DEVICE_TABLE(vkCmdSetDepthCompareOp)
    LOAD_DEVICE_TABLE(vkCmdSetDepthBoundsTestEnable)
    LOAD_DEVICE_TABLE(vkCmdSetStencilTestEnable)
    LOAD_DEVICE_TABLE(vkCmdSetStencilOp)
    LOAD_DEVICE_TABLE(vkCmdSetRasterizerDiscardEnable)
    LOAD_DEVICE_TABLE(vkCmdSetDepthBiasEnable)
    LOAD_DEVICE_TABLE(vkCmdSetPrimitiveRestartEnable)
    LOAD_DEVICE_TABLE(vkGetDeviceBufferMemoryRequirements)
    LOAD_DEVICE_TABLE(vkGetDeviceImageMemoryRequirements)
    LOAD_DEVICE_TABLE(vkGetDeviceImageSparseMemoryRequirements)
    LOAD_DEVICE_TABLE(vkCmdSetLineStipple)
    LOAD_DEVICE_TABLE(vkMapMemory2)
    LOAD_DEVICE_TABLE(vkUnmapMemory2)
    LOAD_DEVICE_TABLE(vkCmdBindIndexBuffer2)
    LOAD_DEVICE_TABLE(vkGetRenderingAreaGranularity)
    LOAD_DEVICE_TABLE(vkGetDeviceImageSubresourceLayout)
    LOAD_DEVICE_TABLE(vkGetImageSubresourceLayout2)
    LOAD_DEVICE_TABLE(vkCmdPushDescriptorSet)
    LOAD_DEVICE_TABLE(vkCmdPushDescriptorSetWithTemplate)
    LOAD_DEVICE_TABLE(vkCmdSetRenderingAttachmentLocations)
    LOAD_DEVICE_TABLE(vkCmdSetRenderingInputAttachmentIndices)
    LOAD_DEVICE_TABLE(vkCmdBindDescriptorSets2)
    LOAD_DEVICE_TABLE(vkCmdPushConstants2)
    LOAD_DEVICE_TABLE(vkCmdPushDescriptorSet2)
    LOAD_DEVICE_TABLE(vkCmdPushDescriptorSetWithTemplate2)
    LOAD_DEVICE_TABLE(vkCopyMemoryToImage)
    LOAD_DEVICE_TABLE(vkCopyImageToMemory)
    LOAD_DEVICE_TABLE(vkCopyImageToImage)
    LOAD_DEVICE_TABLE(vkTransitionImageLayout)
    LOAD_DEVICE_TABLE(vkCreateSwapchainKHR)
    LOAD_DEVICE_TABLE(vkDestroySwapchainKHR)
    LOAD_DEVICE_TABLE(vkGetSwapchainImagesKHR)
    LOAD_DEVICE_TABLE(vkAcquireNextImageKHR)
    LOAD_DEVICE_TABLE(vkQueuePresentKHR)
    LOAD_DEVICE_TABLE(vkGetDeviceGroupPresentCapabilitiesKHR)
    LOAD_DEVICE_TABLE(vkGetDeviceGroupSurfacePresentModesKHR)
    LOAD_DEVICE_TABLE(vkAcquireNextImage2KHR)
    LOAD_DEVICE_TABLE(vkCreateSharedSwapchainsKHR)
    LOAD_DEVICE_TABLE(vkCreateVideoSessionKHR)
    LOAD_DEVICE_TABLE(vkDestroyVideoSessionKHR)
    LOAD_DEVICE_TABLE(vkGetVideoSessionMemoryRequirementsKHR)
    LOAD_DEVICE_TABLE(vkBindVideoSessionMemoryKHR)
    LOAD_DEVICE_TABLE(vkCreateVideoSessionParametersKHR)
    LOAD_DEVICE_TABLE(vkUpdateVideoSessionParametersKHR)
    LOAD_DEVICE_TABLE(vkDestroyVideoSessionParametersKHR)
    LOAD_DEVICE_TABLE(vkCmdBeginVideoCodingKHR)
    LOAD_DEVICE_TABLE(vkCmdEndVideoCodingKHR)
    LOAD_DEVICE_TABLE(vkCmdControlVideoCodingKHR)
    LOAD_DEVICE_TABLE(vkCmdDecodeVideoKHR)
    LOAD_DEVICE_TABLE(vkCmdBeginRenderingKHR)
    LOAD_DEVICE_TABLE(vkCmdEndRenderingKHR)
    LOAD_DEVICE_TABLE(vkGetDeviceGroupPeerMemoryFeaturesKHR)
    LOAD_DEVICE_TABLE(vkCmdSetDeviceMaskKHR)
    LOAD_DEVICE_TABLE(vkCmdDispatchBaseKHR)
    LOAD_DEVICE_TABLE(vkTrimCommandPoolKHR)
    LOAD_DEVICE_TABLE(vkGetMemoryFdKHR)
    LOAD_DEVICE_TABLE(vkGetMemoryFdPropertiesKHR)
    LOAD_DEVICE_TABLE(vkImportSemaphoreFdKHR)
    LOAD_DEVICE_TABLE(vkGetSemaphoreFdKHR)
    LOAD_DEVICE_TABLE(vkCmdPushDescriptorSetKHR)
    LOAD_DEVICE_TABLE(vkCmdPushDescriptorSetWithTemplateKHR)
    LOAD_DEVICE_TABLE(vkCreateDescriptorUpdateTemplateKHR)
    LOAD_DEVICE_TABLE(vkDestroyDescriptorUpdateTemplateKHR)
    LOAD_DEVICE_TABLE(vkUpdateDescriptorSetWithTemplateKHR)
    LOAD_DEVICE_TABLE(vkCreateRenderPass2KHR)
    LOAD_DEVICE_TABLE(vkCmdBeginRenderPass2KHR)
    LOAD_DEVICE_TABLE(vkCmdNextSubpass2KHR)
    LOAD_DEVICE_TABLE(vkCmdEndRenderPass2KHR)
    LOAD_DEVICE_TABLE(vkGetSwapchainStatusKHR)
    LOAD_DEVICE_TABLE(vkImportFenceFdKHR)
    LOAD_DEVICE_TABLE(vkGetFenceFdKHR)
    LOAD_DEVICE_TABLE(vkAcquireProfilingLockKHR)
    LOAD_DEVICE_TABLE(vkReleaseProfilingLockKHR)
    LOAD_DEVICE_TABLE(vkGetImageMemoryRequirements2KHR)
    LOAD_DEVICE_TABLE(vkGetBufferMemoryRequirements2KHR)
    LOAD_DEVICE_TABLE(vkGetImageSparseMemoryRequirements2KHR)
    LOAD_DEVICE_TABLE(vkCreateSamplerYcbcrConversionKHR)
    LOAD_DEVICE_TABLE(vkDestroySamplerYcbcrConversionKHR)
    LOAD_DEVICE_TABLE(vkBindBufferMemory2KHR)
    LOAD_DEVICE_TABLE(vkBindImageMemory2KHR)
    LOAD_DEVICE_TABLE(vkGetDescriptorSetLayoutSupportKHR)
    LOAD_DEVICE_TABLE(vkCmdDrawIndirectCountKHR)
    LOAD_DEVICE_TABLE(vkCmdDrawIndexedIndirectCountKHR)
    LOAD_DEVICE_TABLE(vkGetSemaphoreCounterValueKHR)
    LOAD_DEVICE_TABLE(vkWaitSemaphoresKHR)
    LOAD_DEVICE_TABLE(vkSignalSemaphoreKHR)
    LOAD_DEVICE_TABLE(vkCmdSetFragmentShadingRateKHR)
    LOAD_DEVICE_TABLE(vkCmdSetRenderingAttachmentLocationsKHR)
    LOAD_DEVICE_TABLE(vkCmdSetRenderingInputAttachmentIndicesKHR)
    LOAD_DEVICE_TABLE(vkWaitForPresentKHR)
    LOAD_DEVICE_TABLE(vkGetBufferDeviceAddressKHR)
    LOAD_DEVICE_TABLE(vkGetBufferOpaqueCaptureAddressKHR)
    LOAD_DEVICE_TABLE(vkGetDeviceMemoryOpaqueCaptureAddressKHR)
    LOAD_DEVICE_TABLE(vkCreateDeferredOperationKHR)
    LOAD_DEVICE_TABLE(vkDestroyDeferredOperationKHR)
    LOAD_DEVICE_TABLE(vkGetDeferredOperationMaxConcurrencyKHR)
    LOAD_DEVICE_TABLE(vkGetDeferredOperationResultKHR)
    LOAD_DEVICE_TABLE(vkDeferredOperationJoinKHR)
    LOAD_DEVICE_TABLE(vkGetPipelineExecutablePropertiesKHR)
    LOAD_DEVICE_TABLE(vkGetPipelineExecutableStatisticsKHR)
    LOAD_DEVICE_TABLE(vkGetPipelineExecutableInternalRepresentationsKHR)
    LOAD_DEVICE_TABLE(vkMapMemory2KHR)
    LOAD_DEVICE_TABLE(vkUnmapMemory2KHR)
    LOAD_DEVICE_TABLE(vkGetEncodedVideoSessionParametersKHR)
    LOAD_DEVICE_TABLE(vkCmdEncodeVideoKHR)
    LOAD_DEVICE_TABLE(vkCmdSetEvent2KHR)
    LOAD_DEVICE_TABLE(vkCmdResetEvent2KHR)
    LOAD_DEVICE_TABLE(vkCmdWaitEvents2KHR)
    LOAD_DEVICE_TABLE(vkCmdPipelineBarrier2KHR)
    LOAD_DEVICE_TABLE(vkCmdWriteTimestamp2KHR)
    LOAD_DEVICE_TABLE(vkQueueSubmit2KHR)
    LOAD_DEVICE_TABLE(vkCmdCopyBuffer2KHR)
    LOAD_DEVICE_TABLE(vkCmdCopyImage2KHR)
    LOAD_DEVICE_TABLE(vkCmdCopyBufferToImage2KHR)
    LOAD_DEVICE_TABLE(vkCmdCopyImageToBuffer2KHR)
    LOAD_DEVICE_TABLE(vkCmdBlitImage2KHR)
    LOAD_DEVICE_TABLE(vkCmdResolveImage2KHR)
    LOAD_DEVICE_TABLE(vkCmdTraceRaysIndirect2KHR)
    LOAD_DEVICE_TABLE(vkGetDeviceBufferMemoryRequirementsKHR)
    LOAD_DEVICE_TABLE(vkGetDeviceImageMemoryRequirementsKHR)
    LOAD_DEVICE_TABLE(vkGetDeviceImageSparseMemoryRequirementsKHR)
    LOAD_DEVICE_TABLE(vkCmdBindIndexBuffer2KHR)
    LOAD_DEVICE_TABLE(vkGetRenderingAreaGranularityKHR)
    LOAD_DEVICE_TABLE(vkGetDeviceImageSubresourceLayoutKHR)
    LOAD_DEVICE_TABLE(vkGetImageSubresourceLayout2KHR)
    LOAD_DEVICE_TABLE(vkCreatePipelineBinariesKHR)
    LOAD_DEVICE_TABLE(vkDestroyPipelineBinaryKHR)
    LOAD_DEVICE_TABLE(vkGetPipelineKeyKHR)
    LOAD_DEVICE_TABLE(vkGetPipelineBinaryDataKHR)
    LOAD_DEVICE_TABLE(vkReleaseCapturedPipelineDataKHR)
    LOAD_DEVICE_TABLE(vkCmdSetLineStippleKHR)
    LOAD_DEVICE_TABLE(vkGetCalibratedTimestampsKHR)
    LOAD_DEVICE_TABLE(vkCmdBindDescriptorSets2KHR)
    LOAD_DEVICE_TABLE(vkCmdPushConstants2KHR)
    LOAD_DEVICE_TABLE(vkCmdPushDescriptorSet2KHR)
    LOAD_DEVICE_TABLE(vkCmdPushDescriptorSetWithTemplate2KHR)
    LOAD_DEVICE_TABLE(vkCmdSetDescriptorBufferOffsets2EXT)
    LOAD_DEVICE_TABLE(vkCmdBindDescriptorBufferEmbeddedSamplers2EXT)
    LOAD_DEVICE_TABLE(vkCreateAccelerationStructureKHR)
    LOAD_DEVICE_TABLE(vkDestroyAccelerationStructureKHR)
    LOAD_DEVICE_TABLE(vkCmdBuildAccelerationStructuresKHR)
    LOAD_DEVICE_TABLE(vkCmdBuildAccelerationStructuresIndirectKHR)
    LOAD_DEVICE_TABLE(vkBuildAccelerationStructuresKHR)
    LOAD_DEVICE_TABLE(vkCopyAccelerationStructureKHR)
    LOAD_DEVICE_TABLE(vkCopyAccelerationStructureToMemoryKHR)
    LOAD_DEVICE_TABLE(vkCopyMemoryToAccelerationStructureKHR)
    LOAD_DEVICE_TABLE(vkWriteAccelerationStructuresPropertiesKHR)
    LOAD_DEVICE_TABLE(vkCmdCopyAccelerationStructureKHR)
    LOAD_DEVICE_TABLE(vkCmdCopyAccelerationStructureToMemoryKHR)
    LOAD_DEVICE_TABLE(vkCmdCopyMemoryToAccelerationStructureKHR)
    LOAD_DEVICE_TABLE(vkGetAccelerationStructureDeviceAddressKHR)
    LOAD_DEVICE_TABLE(vkCmdWriteAccelerationStructuresPropertiesKHR)
    LOAD_DEVICE_TABLE(vkGetDeviceAccelerationStructureCompatibilityKHR)
    LOAD_DEVICE_TABLE(vkGetAccelerationStructureBuildSizesKHR)
    LOAD_DEVICE_TABLE(vkCmdTraceRaysKHR)
    LOAD_DEVICE_TABLE(vkCreateRayTracingPipelinesKHR)
    LOAD_DEVICE_TABLE(vkGetRayTracingCaptureReplayShaderGroupHandlesKHR)
    LOAD_DEVICE_TABLE(vkCmdTraceRaysIndirectKHR)
    LOAD_DEVICE_TABLE(vkGetRayTracingShaderGroupStackSizeKHR)
    LOAD_DEVICE_TABLE(vkCmdSetRayTracingPipelineStackSizeKHR)
#undef LOAD_DEVICE_TABLE
}

#ifdef __cplusplus
}
#endif

